// Code generated by ent, DO NOT EDIT.

package radacct

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/mikestefanello/pagoda/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldLTE(FieldID, id))
}

// Acctsessionid applies equality check predicate on the "acctsessionid" field. It's identical to AcctsessionidEQ.
func Acctsessionid(v string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldEQ(FieldAcctsessionid, v))
}

// Acctuniqueid applies equality check predicate on the "acctuniqueid" field. It's identical to AcctuniqueidEQ.
func Acctuniqueid(v string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldEQ(FieldAcctuniqueid, v))
}

// Username applies equality check predicate on the "username" field. It's identical to UsernameEQ.
func Username(v string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldEQ(FieldUsername, v))
}

// Acctstarttime applies equality check predicate on the "acctstarttime" field. It's identical to AcctstarttimeEQ.
func Acctstarttime(v time.Time) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldEQ(FieldAcctstarttime, v))
}

// Acctstoptime applies equality check predicate on the "acctstoptime" field. It's identical to AcctstoptimeEQ.
func Acctstoptime(v time.Time) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldEQ(FieldAcctstoptime, v))
}

// Acctsessiontime applies equality check predicate on the "acctsessiontime" field. It's identical to AcctsessiontimeEQ.
func Acctsessiontime(v uint32) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldEQ(FieldAcctsessiontime, v))
}

// Acctinputoctets applies equality check predicate on the "acctinputoctets" field. It's identical to AcctinputoctetsEQ.
func Acctinputoctets(v int64) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldEQ(FieldAcctinputoctets, v))
}

// Acctoutputoctets applies equality check predicate on the "acctoutputoctets" field. It's identical to AcctoutputoctetsEQ.
func Acctoutputoctets(v int64) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldEQ(FieldAcctoutputoctets, v))
}

// Framedipaddress applies equality check predicate on the "framedipaddress" field. It's identical to FramedipaddressEQ.
func Framedipaddress(v string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldEQ(FieldFramedipaddress, v))
}

// Acctterminatecause applies equality check predicate on the "acctterminatecause" field. It's identical to AcctterminatecauseEQ.
func Acctterminatecause(v string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldEQ(FieldAcctterminatecause, v))
}

// AcctsessionidEQ applies the EQ predicate on the "acctsessionid" field.
func AcctsessionidEQ(v string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldEQ(FieldAcctsessionid, v))
}

// AcctsessionidNEQ applies the NEQ predicate on the "acctsessionid" field.
func AcctsessionidNEQ(v string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldNEQ(FieldAcctsessionid, v))
}

// AcctsessionidIn applies the In predicate on the "acctsessionid" field.
func AcctsessionidIn(vs ...string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldIn(FieldAcctsessionid, vs...))
}

// AcctsessionidNotIn applies the NotIn predicate on the "acctsessionid" field.
func AcctsessionidNotIn(vs ...string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldNotIn(FieldAcctsessionid, vs...))
}

// AcctsessionidGT applies the GT predicate on the "acctsessionid" field.
func AcctsessionidGT(v string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldGT(FieldAcctsessionid, v))
}

// AcctsessionidGTE applies the GTE predicate on the "acctsessionid" field.
func AcctsessionidGTE(v string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldGTE(FieldAcctsessionid, v))
}

// AcctsessionidLT applies the LT predicate on the "acctsessionid" field.
func AcctsessionidLT(v string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldLT(FieldAcctsessionid, v))
}

// AcctsessionidLTE applies the LTE predicate on the "acctsessionid" field.
func AcctsessionidLTE(v string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldLTE(FieldAcctsessionid, v))
}

// AcctsessionidContains applies the Contains predicate on the "acctsessionid" field.
func AcctsessionidContains(v string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldContains(FieldAcctsessionid, v))
}

// AcctsessionidHasPrefix applies the HasPrefix predicate on the "acctsessionid" field.
func AcctsessionidHasPrefix(v string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldHasPrefix(FieldAcctsessionid, v))
}

// AcctsessionidHasSuffix applies the HasSuffix predicate on the "acctsessionid" field.
func AcctsessionidHasSuffix(v string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldHasSuffix(FieldAcctsessionid, v))
}

// AcctsessionidEqualFold applies the EqualFold predicate on the "acctsessionid" field.
func AcctsessionidEqualFold(v string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldEqualFold(FieldAcctsessionid, v))
}

// AcctsessionidContainsFold applies the ContainsFold predicate on the "acctsessionid" field.
func AcctsessionidContainsFold(v string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldContainsFold(FieldAcctsessionid, v))
}

// AcctuniqueidEQ applies the EQ predicate on the "acctuniqueid" field.
func AcctuniqueidEQ(v string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldEQ(FieldAcctuniqueid, v))
}

// AcctuniqueidNEQ applies the NEQ predicate on the "acctuniqueid" field.
func AcctuniqueidNEQ(v string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldNEQ(FieldAcctuniqueid, v))
}

// AcctuniqueidIn applies the In predicate on the "acctuniqueid" field.
func AcctuniqueidIn(vs ...string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldIn(FieldAcctuniqueid, vs...))
}

// AcctuniqueidNotIn applies the NotIn predicate on the "acctuniqueid" field.
func AcctuniqueidNotIn(vs ...string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldNotIn(FieldAcctuniqueid, vs...))
}

// AcctuniqueidGT applies the GT predicate on the "acctuniqueid" field.
func AcctuniqueidGT(v string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldGT(FieldAcctuniqueid, v))
}

// AcctuniqueidGTE applies the GTE predicate on the "acctuniqueid" field.
func AcctuniqueidGTE(v string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldGTE(FieldAcctuniqueid, v))
}

// AcctuniqueidLT applies the LT predicate on the "acctuniqueid" field.
func AcctuniqueidLT(v string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldLT(FieldAcctuniqueid, v))
}

// AcctuniqueidLTE applies the LTE predicate on the "acctuniqueid" field.
func AcctuniqueidLTE(v string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldLTE(FieldAcctuniqueid, v))
}

// AcctuniqueidContains applies the Contains predicate on the "acctuniqueid" field.
func AcctuniqueidContains(v string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldContains(FieldAcctuniqueid, v))
}

// AcctuniqueidHasPrefix applies the HasPrefix predicate on the "acctuniqueid" field.
func AcctuniqueidHasPrefix(v string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldHasPrefix(FieldAcctuniqueid, v))
}

// AcctuniqueidHasSuffix applies the HasSuffix predicate on the "acctuniqueid" field.
func AcctuniqueidHasSuffix(v string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldHasSuffix(FieldAcctuniqueid, v))
}

// AcctuniqueidEqualFold applies the EqualFold predicate on the "acctuniqueid" field.
func AcctuniqueidEqualFold(v string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldEqualFold(FieldAcctuniqueid, v))
}

// AcctuniqueidContainsFold applies the ContainsFold predicate on the "acctuniqueid" field.
func AcctuniqueidContainsFold(v string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldContainsFold(FieldAcctuniqueid, v))
}

// UsernameEQ applies the EQ predicate on the "username" field.
func UsernameEQ(v string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldEQ(FieldUsername, v))
}

// UsernameNEQ applies the NEQ predicate on the "username" field.
func UsernameNEQ(v string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldNEQ(FieldUsername, v))
}

// UsernameIn applies the In predicate on the "username" field.
func UsernameIn(vs ...string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldIn(FieldUsername, vs...))
}

// UsernameNotIn applies the NotIn predicate on the "username" field.
func UsernameNotIn(vs ...string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldNotIn(FieldUsername, vs...))
}

// UsernameGT applies the GT predicate on the "username" field.
func UsernameGT(v string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldGT(FieldUsername, v))
}

// UsernameGTE applies the GTE predicate on the "username" field.
func UsernameGTE(v string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldGTE(FieldUsername, v))
}

// UsernameLT applies the LT predicate on the "username" field.
func UsernameLT(v string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldLT(FieldUsername, v))
}

// UsernameLTE applies the LTE predicate on the "username" field.
func UsernameLTE(v string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldLTE(FieldUsername, v))
}

// UsernameContains applies the Contains predicate on the "username" field.
func UsernameContains(v string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldContains(FieldUsername, v))
}

// UsernameHasPrefix applies the HasPrefix predicate on the "username" field.
func UsernameHasPrefix(v string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldHasPrefix(FieldUsername, v))
}

// UsernameHasSuffix applies the HasSuffix predicate on the "username" field.
func UsernameHasSuffix(v string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldHasSuffix(FieldUsername, v))
}

// UsernameEqualFold applies the EqualFold predicate on the "username" field.
func UsernameEqualFold(v string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldEqualFold(FieldUsername, v))
}

// UsernameContainsFold applies the ContainsFold predicate on the "username" field.
func UsernameContainsFold(v string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldContainsFold(FieldUsername, v))
}

// AcctstarttimeEQ applies the EQ predicate on the "acctstarttime" field.
func AcctstarttimeEQ(v time.Time) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldEQ(FieldAcctstarttime, v))
}

// AcctstarttimeNEQ applies the NEQ predicate on the "acctstarttime" field.
func AcctstarttimeNEQ(v time.Time) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldNEQ(FieldAcctstarttime, v))
}

// AcctstarttimeIn applies the In predicate on the "acctstarttime" field.
func AcctstarttimeIn(vs ...time.Time) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldIn(FieldAcctstarttime, vs...))
}

// AcctstarttimeNotIn applies the NotIn predicate on the "acctstarttime" field.
func AcctstarttimeNotIn(vs ...time.Time) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldNotIn(FieldAcctstarttime, vs...))
}

// AcctstarttimeGT applies the GT predicate on the "acctstarttime" field.
func AcctstarttimeGT(v time.Time) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldGT(FieldAcctstarttime, v))
}

// AcctstarttimeGTE applies the GTE predicate on the "acctstarttime" field.
func AcctstarttimeGTE(v time.Time) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldGTE(FieldAcctstarttime, v))
}

// AcctstarttimeLT applies the LT predicate on the "acctstarttime" field.
func AcctstarttimeLT(v time.Time) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldLT(FieldAcctstarttime, v))
}

// AcctstarttimeLTE applies the LTE predicate on the "acctstarttime" field.
func AcctstarttimeLTE(v time.Time) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldLTE(FieldAcctstarttime, v))
}

// AcctstarttimeIsNil applies the IsNil predicate on the "acctstarttime" field.
func AcctstarttimeIsNil() predicate.RadAcct {
	return predicate.RadAcct(sql.FieldIsNull(FieldAcctstarttime))
}

// AcctstarttimeNotNil applies the NotNil predicate on the "acctstarttime" field.
func AcctstarttimeNotNil() predicate.RadAcct {
	return predicate.RadAcct(sql.FieldNotNull(FieldAcctstarttime))
}

// AcctstoptimeEQ applies the EQ predicate on the "acctstoptime" field.
func AcctstoptimeEQ(v time.Time) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldEQ(FieldAcctstoptime, v))
}

// AcctstoptimeNEQ applies the NEQ predicate on the "acctstoptime" field.
func AcctstoptimeNEQ(v time.Time) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldNEQ(FieldAcctstoptime, v))
}

// AcctstoptimeIn applies the In predicate on the "acctstoptime" field.
func AcctstoptimeIn(vs ...time.Time) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldIn(FieldAcctstoptime, vs...))
}

// AcctstoptimeNotIn applies the NotIn predicate on the "acctstoptime" field.
func AcctstoptimeNotIn(vs ...time.Time) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldNotIn(FieldAcctstoptime, vs...))
}

// AcctstoptimeGT applies the GT predicate on the "acctstoptime" field.
func AcctstoptimeGT(v time.Time) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldGT(FieldAcctstoptime, v))
}

// AcctstoptimeGTE applies the GTE predicate on the "acctstoptime" field.
func AcctstoptimeGTE(v time.Time) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldGTE(FieldAcctstoptime, v))
}

// AcctstoptimeLT applies the LT predicate on the "acctstoptime" field.
func AcctstoptimeLT(v time.Time) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldLT(FieldAcctstoptime, v))
}

// AcctstoptimeLTE applies the LTE predicate on the "acctstoptime" field.
func AcctstoptimeLTE(v time.Time) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldLTE(FieldAcctstoptime, v))
}

// AcctstoptimeIsNil applies the IsNil predicate on the "acctstoptime" field.
func AcctstoptimeIsNil() predicate.RadAcct {
	return predicate.RadAcct(sql.FieldIsNull(FieldAcctstoptime))
}

// AcctstoptimeNotNil applies the NotNil predicate on the "acctstoptime" field.
func AcctstoptimeNotNil() predicate.RadAcct {
	return predicate.RadAcct(sql.FieldNotNull(FieldAcctstoptime))
}

// AcctsessiontimeEQ applies the EQ predicate on the "acctsessiontime" field.
func AcctsessiontimeEQ(v uint32) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldEQ(FieldAcctsessiontime, v))
}

// AcctsessiontimeNEQ applies the NEQ predicate on the "acctsessiontime" field.
func AcctsessiontimeNEQ(v uint32) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldNEQ(FieldAcctsessiontime, v))
}

// AcctsessiontimeIn applies the In predicate on the "acctsessiontime" field.
func AcctsessiontimeIn(vs ...uint32) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldIn(FieldAcctsessiontime, vs...))
}

// AcctsessiontimeNotIn applies the NotIn predicate on the "acctsessiontime" field.
func AcctsessiontimeNotIn(vs ...uint32) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldNotIn(FieldAcctsessiontime, vs...))
}

// AcctsessiontimeGT applies the GT predicate on the "acctsessiontime" field.
func AcctsessiontimeGT(v uint32) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldGT(FieldAcctsessiontime, v))
}

// AcctsessiontimeGTE applies the GTE predicate on the "acctsessiontime" field.
func AcctsessiontimeGTE(v uint32) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldGTE(FieldAcctsessiontime, v))
}

// AcctsessiontimeLT applies the LT predicate on the "acctsessiontime" field.
func AcctsessiontimeLT(v uint32) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldLT(FieldAcctsessiontime, v))
}

// AcctsessiontimeLTE applies the LTE predicate on the "acctsessiontime" field.
func AcctsessiontimeLTE(v uint32) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldLTE(FieldAcctsessiontime, v))
}

// AcctsessiontimeIsNil applies the IsNil predicate on the "acctsessiontime" field.
func AcctsessiontimeIsNil() predicate.RadAcct {
	return predicate.RadAcct(sql.FieldIsNull(FieldAcctsessiontime))
}

// AcctsessiontimeNotNil applies the NotNil predicate on the "acctsessiontime" field.
func AcctsessiontimeNotNil() predicate.RadAcct {
	return predicate.RadAcct(sql.FieldNotNull(FieldAcctsessiontime))
}

// AcctinputoctetsEQ applies the EQ predicate on the "acctinputoctets" field.
func AcctinputoctetsEQ(v int64) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldEQ(FieldAcctinputoctets, v))
}

// AcctinputoctetsNEQ applies the NEQ predicate on the "acctinputoctets" field.
func AcctinputoctetsNEQ(v int64) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldNEQ(FieldAcctinputoctets, v))
}

// AcctinputoctetsIn applies the In predicate on the "acctinputoctets" field.
func AcctinputoctetsIn(vs ...int64) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldIn(FieldAcctinputoctets, vs...))
}

// AcctinputoctetsNotIn applies the NotIn predicate on the "acctinputoctets" field.
func AcctinputoctetsNotIn(vs ...int64) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldNotIn(FieldAcctinputoctets, vs...))
}

// AcctinputoctetsGT applies the GT predicate on the "acctinputoctets" field.
func AcctinputoctetsGT(v int64) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldGT(FieldAcctinputoctets, v))
}

// AcctinputoctetsGTE applies the GTE predicate on the "acctinputoctets" field.
func AcctinputoctetsGTE(v int64) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldGTE(FieldAcctinputoctets, v))
}

// AcctinputoctetsLT applies the LT predicate on the "acctinputoctets" field.
func AcctinputoctetsLT(v int64) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldLT(FieldAcctinputoctets, v))
}

// AcctinputoctetsLTE applies the LTE predicate on the "acctinputoctets" field.
func AcctinputoctetsLTE(v int64) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldLTE(FieldAcctinputoctets, v))
}

// AcctinputoctetsIsNil applies the IsNil predicate on the "acctinputoctets" field.
func AcctinputoctetsIsNil() predicate.RadAcct {
	return predicate.RadAcct(sql.FieldIsNull(FieldAcctinputoctets))
}

// AcctinputoctetsNotNil applies the NotNil predicate on the "acctinputoctets" field.
func AcctinputoctetsNotNil() predicate.RadAcct {
	return predicate.RadAcct(sql.FieldNotNull(FieldAcctinputoctets))
}

// AcctoutputoctetsEQ applies the EQ predicate on the "acctoutputoctets" field.
func AcctoutputoctetsEQ(v int64) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldEQ(FieldAcctoutputoctets, v))
}

// AcctoutputoctetsNEQ applies the NEQ predicate on the "acctoutputoctets" field.
func AcctoutputoctetsNEQ(v int64) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldNEQ(FieldAcctoutputoctets, v))
}

// AcctoutputoctetsIn applies the In predicate on the "acctoutputoctets" field.
func AcctoutputoctetsIn(vs ...int64) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldIn(FieldAcctoutputoctets, vs...))
}

// AcctoutputoctetsNotIn applies the NotIn predicate on the "acctoutputoctets" field.
func AcctoutputoctetsNotIn(vs ...int64) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldNotIn(FieldAcctoutputoctets, vs...))
}

// AcctoutputoctetsGT applies the GT predicate on the "acctoutputoctets" field.
func AcctoutputoctetsGT(v int64) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldGT(FieldAcctoutputoctets, v))
}

// AcctoutputoctetsGTE applies the GTE predicate on the "acctoutputoctets" field.
func AcctoutputoctetsGTE(v int64) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldGTE(FieldAcctoutputoctets, v))
}

// AcctoutputoctetsLT applies the LT predicate on the "acctoutputoctets" field.
func AcctoutputoctetsLT(v int64) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldLT(FieldAcctoutputoctets, v))
}

// AcctoutputoctetsLTE applies the LTE predicate on the "acctoutputoctets" field.
func AcctoutputoctetsLTE(v int64) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldLTE(FieldAcctoutputoctets, v))
}

// AcctoutputoctetsIsNil applies the IsNil predicate on the "acctoutputoctets" field.
func AcctoutputoctetsIsNil() predicate.RadAcct {
	return predicate.RadAcct(sql.FieldIsNull(FieldAcctoutputoctets))
}

// AcctoutputoctetsNotNil applies the NotNil predicate on the "acctoutputoctets" field.
func AcctoutputoctetsNotNil() predicate.RadAcct {
	return predicate.RadAcct(sql.FieldNotNull(FieldAcctoutputoctets))
}

// FramedipaddressEQ applies the EQ predicate on the "framedipaddress" field.
func FramedipaddressEQ(v string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldEQ(FieldFramedipaddress, v))
}

// FramedipaddressNEQ applies the NEQ predicate on the "framedipaddress" field.
func FramedipaddressNEQ(v string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldNEQ(FieldFramedipaddress, v))
}

// FramedipaddressIn applies the In predicate on the "framedipaddress" field.
func FramedipaddressIn(vs ...string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldIn(FieldFramedipaddress, vs...))
}

// FramedipaddressNotIn applies the NotIn predicate on the "framedipaddress" field.
func FramedipaddressNotIn(vs ...string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldNotIn(FieldFramedipaddress, vs...))
}

// FramedipaddressGT applies the GT predicate on the "framedipaddress" field.
func FramedipaddressGT(v string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldGT(FieldFramedipaddress, v))
}

// FramedipaddressGTE applies the GTE predicate on the "framedipaddress" field.
func FramedipaddressGTE(v string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldGTE(FieldFramedipaddress, v))
}

// FramedipaddressLT applies the LT predicate on the "framedipaddress" field.
func FramedipaddressLT(v string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldLT(FieldFramedipaddress, v))
}

// FramedipaddressLTE applies the LTE predicate on the "framedipaddress" field.
func FramedipaddressLTE(v string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldLTE(FieldFramedipaddress, v))
}

// FramedipaddressContains applies the Contains predicate on the "framedipaddress" field.
func FramedipaddressContains(v string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldContains(FieldFramedipaddress, v))
}

// FramedipaddressHasPrefix applies the HasPrefix predicate on the "framedipaddress" field.
func FramedipaddressHasPrefix(v string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldHasPrefix(FieldFramedipaddress, v))
}

// FramedipaddressHasSuffix applies the HasSuffix predicate on the "framedipaddress" field.
func FramedipaddressHasSuffix(v string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldHasSuffix(FieldFramedipaddress, v))
}

// FramedipaddressEqualFold applies the EqualFold predicate on the "framedipaddress" field.
func FramedipaddressEqualFold(v string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldEqualFold(FieldFramedipaddress, v))
}

// FramedipaddressContainsFold applies the ContainsFold predicate on the "framedipaddress" field.
func FramedipaddressContainsFold(v string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldContainsFold(FieldFramedipaddress, v))
}

// AcctterminatecauseEQ applies the EQ predicate on the "acctterminatecause" field.
func AcctterminatecauseEQ(v string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldEQ(FieldAcctterminatecause, v))
}

// AcctterminatecauseNEQ applies the NEQ predicate on the "acctterminatecause" field.
func AcctterminatecauseNEQ(v string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldNEQ(FieldAcctterminatecause, v))
}

// AcctterminatecauseIn applies the In predicate on the "acctterminatecause" field.
func AcctterminatecauseIn(vs ...string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldIn(FieldAcctterminatecause, vs...))
}

// AcctterminatecauseNotIn applies the NotIn predicate on the "acctterminatecause" field.
func AcctterminatecauseNotIn(vs ...string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldNotIn(FieldAcctterminatecause, vs...))
}

// AcctterminatecauseGT applies the GT predicate on the "acctterminatecause" field.
func AcctterminatecauseGT(v string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldGT(FieldAcctterminatecause, v))
}

// AcctterminatecauseGTE applies the GTE predicate on the "acctterminatecause" field.
func AcctterminatecauseGTE(v string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldGTE(FieldAcctterminatecause, v))
}

// AcctterminatecauseLT applies the LT predicate on the "acctterminatecause" field.
func AcctterminatecauseLT(v string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldLT(FieldAcctterminatecause, v))
}

// AcctterminatecauseLTE applies the LTE predicate on the "acctterminatecause" field.
func AcctterminatecauseLTE(v string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldLTE(FieldAcctterminatecause, v))
}

// AcctterminatecauseContains applies the Contains predicate on the "acctterminatecause" field.
func AcctterminatecauseContains(v string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldContains(FieldAcctterminatecause, v))
}

// AcctterminatecauseHasPrefix applies the HasPrefix predicate on the "acctterminatecause" field.
func AcctterminatecauseHasPrefix(v string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldHasPrefix(FieldAcctterminatecause, v))
}

// AcctterminatecauseHasSuffix applies the HasSuffix predicate on the "acctterminatecause" field.
func AcctterminatecauseHasSuffix(v string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldHasSuffix(FieldAcctterminatecause, v))
}

// AcctterminatecauseEqualFold applies the EqualFold predicate on the "acctterminatecause" field.
func AcctterminatecauseEqualFold(v string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldEqualFold(FieldAcctterminatecause, v))
}

// AcctterminatecauseContainsFold applies the ContainsFold predicate on the "acctterminatecause" field.
func AcctterminatecauseContainsFold(v string) predicate.RadAcct {
	return predicate.RadAcct(sql.FieldContainsFold(FieldAcctterminatecause, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RadAcct) predicate.RadAcct {
	return predicate.RadAcct(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RadAcct) predicate.RadAcct {
	return predicate.RadAcct(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RadAcct) predicate.RadAcct {
	return predicate.RadAcct(sql.NotPredicates(p))
}
