// Code generated by ent, DO NOT EDIT.

package clientuser

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/mikestefanello/pagoda/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEQ(FieldName, v))
}

// Username applies equality check predicate on the "username" field. It's identical to UsernameEQ.
func Username(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEQ(FieldUsername, v))
}

// Password applies equality check predicate on the "password" field. It's identical to PasswordEQ.
func Password(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEQ(FieldPassword, v))
}

// MobileNumber applies equality check predicate on the "mobile_number" field. It's identical to MobileNumberEQ.
func MobileNumber(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEQ(FieldMobileNumber, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEQ(FieldEmail, v))
}

// Photo applies equality check predicate on the "photo" field. It's identical to PhotoEQ.
func Photo(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEQ(FieldPhoto, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEQ(FieldDescription, v))
}

// Balance applies equality check predicate on the "balance" field. It's identical to BalanceEQ.
func Balance(v float64) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEQ(FieldBalance, v))
}

// AddressLine1 applies equality check predicate on the "address_line1" field. It's identical to AddressLine1EQ.
func AddressLine1(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEQ(FieldAddressLine1, v))
}

// AddressLine2 applies equality check predicate on the "address_line2" field. It's identical to AddressLine2EQ.
func AddressLine2(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEQ(FieldAddressLine2, v))
}

// City applies equality check predicate on the "city" field. It's identical to CityEQ.
func City(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEQ(FieldCity, v))
}

// District applies equality check predicate on the "district" field. It's identical to DistrictEQ.
func District(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEQ(FieldDistrict, v))
}

// Upazila applies equality check predicate on the "upazila" field. It's identical to UpazilaEQ.
func Upazila(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEQ(FieldUpazila, v))
}

// UnionName applies equality check predicate on the "union_name" field. It's identical to UnionNameEQ.
func UnionName(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEQ(FieldUnionName, v))
}

// Zip applies equality check predicate on the "zip" field. It's identical to ZipEQ.
func Zip(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEQ(FieldZip, v))
}

// PaymentDate applies equality check predicate on the "payment_date" field. It's identical to PaymentDateEQ.
func PaymentDate(v time.Time) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEQ(FieldPaymentDate, v))
}

// PaymentType applies equality check predicate on the "payment_type" field. It's identical to PaymentTypeEQ.
func PaymentType(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEQ(FieldPaymentType, v))
}

// AutoRenew applies equality check predicate on the "auto_renew" field. It's identical to AutoRenewEQ.
func AutoRenew(v bool) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEQ(FieldAutoRenew, v))
}

// CName applies equality check predicate on the "c_name" field. It's identical to CNameEQ.
func CName(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEQ(FieldCName, v))
}

// VendorID applies equality check predicate on the "vendor_id" field. It's identical to VendorIDEQ.
func VendorID(v int) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEQ(FieldVendorID, v))
}

// PackagePool applies equality check predicate on the "package_pool" field. It's identical to PackagePoolEQ.
func PackagePool(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEQ(FieldPackagePool, v))
}

// UserProfile applies equality check predicate on the "user_profile" field. It's identical to UserProfileEQ.
func UserProfile(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEQ(FieldUserProfile, v))
}

// NextUserProfile applies equality check predicate on the "next_user_profile" field. It's identical to NextUserProfileEQ.
func NextUserProfile(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEQ(FieldNextUserProfile, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEQ(FieldUpdatedBy, v))
}

// CreatedDate applies equality check predicate on the "created_date" field. It's identical to CreatedDateEQ.
func CreatedDate(v time.Time) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEQ(FieldCreatedDate, v))
}

// UpdatedDate applies equality check predicate on the "updated_date" field. It's identical to UpdatedDateEQ.
func UpdatedDate(v time.Time) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEQ(FieldUpdatedDate, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldContainsFold(FieldName, v))
}

// UsernameEQ applies the EQ predicate on the "username" field.
func UsernameEQ(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEQ(FieldUsername, v))
}

// UsernameNEQ applies the NEQ predicate on the "username" field.
func UsernameNEQ(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNEQ(FieldUsername, v))
}

// UsernameIn applies the In predicate on the "username" field.
func UsernameIn(vs ...string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldIn(FieldUsername, vs...))
}

// UsernameNotIn applies the NotIn predicate on the "username" field.
func UsernameNotIn(vs ...string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNotIn(FieldUsername, vs...))
}

// UsernameGT applies the GT predicate on the "username" field.
func UsernameGT(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldGT(FieldUsername, v))
}

// UsernameGTE applies the GTE predicate on the "username" field.
func UsernameGTE(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldGTE(FieldUsername, v))
}

// UsernameLT applies the LT predicate on the "username" field.
func UsernameLT(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldLT(FieldUsername, v))
}

// UsernameLTE applies the LTE predicate on the "username" field.
func UsernameLTE(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldLTE(FieldUsername, v))
}

// UsernameContains applies the Contains predicate on the "username" field.
func UsernameContains(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldContains(FieldUsername, v))
}

// UsernameHasPrefix applies the HasPrefix predicate on the "username" field.
func UsernameHasPrefix(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldHasPrefix(FieldUsername, v))
}

// UsernameHasSuffix applies the HasSuffix predicate on the "username" field.
func UsernameHasSuffix(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldHasSuffix(FieldUsername, v))
}

// UsernameEqualFold applies the EqualFold predicate on the "username" field.
func UsernameEqualFold(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEqualFold(FieldUsername, v))
}

// UsernameContainsFold applies the ContainsFold predicate on the "username" field.
func UsernameContainsFold(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldContainsFold(FieldUsername, v))
}

// PasswordEQ applies the EQ predicate on the "password" field.
func PasswordEQ(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEQ(FieldPassword, v))
}

// PasswordNEQ applies the NEQ predicate on the "password" field.
func PasswordNEQ(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNEQ(FieldPassword, v))
}

// PasswordIn applies the In predicate on the "password" field.
func PasswordIn(vs ...string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldIn(FieldPassword, vs...))
}

// PasswordNotIn applies the NotIn predicate on the "password" field.
func PasswordNotIn(vs ...string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNotIn(FieldPassword, vs...))
}

// PasswordGT applies the GT predicate on the "password" field.
func PasswordGT(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldGT(FieldPassword, v))
}

// PasswordGTE applies the GTE predicate on the "password" field.
func PasswordGTE(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldGTE(FieldPassword, v))
}

// PasswordLT applies the LT predicate on the "password" field.
func PasswordLT(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldLT(FieldPassword, v))
}

// PasswordLTE applies the LTE predicate on the "password" field.
func PasswordLTE(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldLTE(FieldPassword, v))
}

// PasswordContains applies the Contains predicate on the "password" field.
func PasswordContains(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldContains(FieldPassword, v))
}

// PasswordHasPrefix applies the HasPrefix predicate on the "password" field.
func PasswordHasPrefix(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldHasPrefix(FieldPassword, v))
}

// PasswordHasSuffix applies the HasSuffix predicate on the "password" field.
func PasswordHasSuffix(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldHasSuffix(FieldPassword, v))
}

// PasswordEqualFold applies the EqualFold predicate on the "password" field.
func PasswordEqualFold(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEqualFold(FieldPassword, v))
}

// PasswordContainsFold applies the ContainsFold predicate on the "password" field.
func PasswordContainsFold(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldContainsFold(FieldPassword, v))
}

// MobileNumberEQ applies the EQ predicate on the "mobile_number" field.
func MobileNumberEQ(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEQ(FieldMobileNumber, v))
}

// MobileNumberNEQ applies the NEQ predicate on the "mobile_number" field.
func MobileNumberNEQ(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNEQ(FieldMobileNumber, v))
}

// MobileNumberIn applies the In predicate on the "mobile_number" field.
func MobileNumberIn(vs ...string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldIn(FieldMobileNumber, vs...))
}

// MobileNumberNotIn applies the NotIn predicate on the "mobile_number" field.
func MobileNumberNotIn(vs ...string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNotIn(FieldMobileNumber, vs...))
}

// MobileNumberGT applies the GT predicate on the "mobile_number" field.
func MobileNumberGT(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldGT(FieldMobileNumber, v))
}

// MobileNumberGTE applies the GTE predicate on the "mobile_number" field.
func MobileNumberGTE(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldGTE(FieldMobileNumber, v))
}

// MobileNumberLT applies the LT predicate on the "mobile_number" field.
func MobileNumberLT(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldLT(FieldMobileNumber, v))
}

// MobileNumberLTE applies the LTE predicate on the "mobile_number" field.
func MobileNumberLTE(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldLTE(FieldMobileNumber, v))
}

// MobileNumberContains applies the Contains predicate on the "mobile_number" field.
func MobileNumberContains(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldContains(FieldMobileNumber, v))
}

// MobileNumberHasPrefix applies the HasPrefix predicate on the "mobile_number" field.
func MobileNumberHasPrefix(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldHasPrefix(FieldMobileNumber, v))
}

// MobileNumberHasSuffix applies the HasSuffix predicate on the "mobile_number" field.
func MobileNumberHasSuffix(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldHasSuffix(FieldMobileNumber, v))
}

// MobileNumberEqualFold applies the EqualFold predicate on the "mobile_number" field.
func MobileNumberEqualFold(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEqualFold(FieldMobileNumber, v))
}

// MobileNumberContainsFold applies the ContainsFold predicate on the "mobile_number" field.
func MobileNumberContainsFold(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldContainsFold(FieldMobileNumber, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldContainsFold(FieldEmail, v))
}

// PhotoEQ applies the EQ predicate on the "photo" field.
func PhotoEQ(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEQ(FieldPhoto, v))
}

// PhotoNEQ applies the NEQ predicate on the "photo" field.
func PhotoNEQ(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNEQ(FieldPhoto, v))
}

// PhotoIn applies the In predicate on the "photo" field.
func PhotoIn(vs ...string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldIn(FieldPhoto, vs...))
}

// PhotoNotIn applies the NotIn predicate on the "photo" field.
func PhotoNotIn(vs ...string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNotIn(FieldPhoto, vs...))
}

// PhotoGT applies the GT predicate on the "photo" field.
func PhotoGT(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldGT(FieldPhoto, v))
}

// PhotoGTE applies the GTE predicate on the "photo" field.
func PhotoGTE(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldGTE(FieldPhoto, v))
}

// PhotoLT applies the LT predicate on the "photo" field.
func PhotoLT(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldLT(FieldPhoto, v))
}

// PhotoLTE applies the LTE predicate on the "photo" field.
func PhotoLTE(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldLTE(FieldPhoto, v))
}

// PhotoContains applies the Contains predicate on the "photo" field.
func PhotoContains(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldContains(FieldPhoto, v))
}

// PhotoHasPrefix applies the HasPrefix predicate on the "photo" field.
func PhotoHasPrefix(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldHasPrefix(FieldPhoto, v))
}

// PhotoHasSuffix applies the HasSuffix predicate on the "photo" field.
func PhotoHasSuffix(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldHasSuffix(FieldPhoto, v))
}

// PhotoIsNil applies the IsNil predicate on the "photo" field.
func PhotoIsNil() predicate.ClientUser {
	return predicate.ClientUser(sql.FieldIsNull(FieldPhoto))
}

// PhotoNotNil applies the NotNil predicate on the "photo" field.
func PhotoNotNil() predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNotNull(FieldPhoto))
}

// PhotoEqualFold applies the EqualFold predicate on the "photo" field.
func PhotoEqualFold(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEqualFold(FieldPhoto, v))
}

// PhotoContainsFold applies the ContainsFold predicate on the "photo" field.
func PhotoContainsFold(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldContainsFold(FieldPhoto, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.ClientUser {
	return predicate.ClientUser(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldContainsFold(FieldDescription, v))
}

// BalanceEQ applies the EQ predicate on the "balance" field.
func BalanceEQ(v float64) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEQ(FieldBalance, v))
}

// BalanceNEQ applies the NEQ predicate on the "balance" field.
func BalanceNEQ(v float64) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNEQ(FieldBalance, v))
}

// BalanceIn applies the In predicate on the "balance" field.
func BalanceIn(vs ...float64) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldIn(FieldBalance, vs...))
}

// BalanceNotIn applies the NotIn predicate on the "balance" field.
func BalanceNotIn(vs ...float64) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNotIn(FieldBalance, vs...))
}

// BalanceGT applies the GT predicate on the "balance" field.
func BalanceGT(v float64) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldGT(FieldBalance, v))
}

// BalanceGTE applies the GTE predicate on the "balance" field.
func BalanceGTE(v float64) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldGTE(FieldBalance, v))
}

// BalanceLT applies the LT predicate on the "balance" field.
func BalanceLT(v float64) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldLT(FieldBalance, v))
}

// BalanceLTE applies the LTE predicate on the "balance" field.
func BalanceLTE(v float64) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldLTE(FieldBalance, v))
}

// AddressLine1EQ applies the EQ predicate on the "address_line1" field.
func AddressLine1EQ(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEQ(FieldAddressLine1, v))
}

// AddressLine1NEQ applies the NEQ predicate on the "address_line1" field.
func AddressLine1NEQ(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNEQ(FieldAddressLine1, v))
}

// AddressLine1In applies the In predicate on the "address_line1" field.
func AddressLine1In(vs ...string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldIn(FieldAddressLine1, vs...))
}

// AddressLine1NotIn applies the NotIn predicate on the "address_line1" field.
func AddressLine1NotIn(vs ...string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNotIn(FieldAddressLine1, vs...))
}

// AddressLine1GT applies the GT predicate on the "address_line1" field.
func AddressLine1GT(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldGT(FieldAddressLine1, v))
}

// AddressLine1GTE applies the GTE predicate on the "address_line1" field.
func AddressLine1GTE(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldGTE(FieldAddressLine1, v))
}

// AddressLine1LT applies the LT predicate on the "address_line1" field.
func AddressLine1LT(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldLT(FieldAddressLine1, v))
}

// AddressLine1LTE applies the LTE predicate on the "address_line1" field.
func AddressLine1LTE(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldLTE(FieldAddressLine1, v))
}

// AddressLine1Contains applies the Contains predicate on the "address_line1" field.
func AddressLine1Contains(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldContains(FieldAddressLine1, v))
}

// AddressLine1HasPrefix applies the HasPrefix predicate on the "address_line1" field.
func AddressLine1HasPrefix(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldHasPrefix(FieldAddressLine1, v))
}

// AddressLine1HasSuffix applies the HasSuffix predicate on the "address_line1" field.
func AddressLine1HasSuffix(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldHasSuffix(FieldAddressLine1, v))
}

// AddressLine1IsNil applies the IsNil predicate on the "address_line1" field.
func AddressLine1IsNil() predicate.ClientUser {
	return predicate.ClientUser(sql.FieldIsNull(FieldAddressLine1))
}

// AddressLine1NotNil applies the NotNil predicate on the "address_line1" field.
func AddressLine1NotNil() predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNotNull(FieldAddressLine1))
}

// AddressLine1EqualFold applies the EqualFold predicate on the "address_line1" field.
func AddressLine1EqualFold(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEqualFold(FieldAddressLine1, v))
}

// AddressLine1ContainsFold applies the ContainsFold predicate on the "address_line1" field.
func AddressLine1ContainsFold(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldContainsFold(FieldAddressLine1, v))
}

// AddressLine2EQ applies the EQ predicate on the "address_line2" field.
func AddressLine2EQ(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEQ(FieldAddressLine2, v))
}

// AddressLine2NEQ applies the NEQ predicate on the "address_line2" field.
func AddressLine2NEQ(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNEQ(FieldAddressLine2, v))
}

// AddressLine2In applies the In predicate on the "address_line2" field.
func AddressLine2In(vs ...string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldIn(FieldAddressLine2, vs...))
}

// AddressLine2NotIn applies the NotIn predicate on the "address_line2" field.
func AddressLine2NotIn(vs ...string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNotIn(FieldAddressLine2, vs...))
}

// AddressLine2GT applies the GT predicate on the "address_line2" field.
func AddressLine2GT(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldGT(FieldAddressLine2, v))
}

// AddressLine2GTE applies the GTE predicate on the "address_line2" field.
func AddressLine2GTE(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldGTE(FieldAddressLine2, v))
}

// AddressLine2LT applies the LT predicate on the "address_line2" field.
func AddressLine2LT(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldLT(FieldAddressLine2, v))
}

// AddressLine2LTE applies the LTE predicate on the "address_line2" field.
func AddressLine2LTE(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldLTE(FieldAddressLine2, v))
}

// AddressLine2Contains applies the Contains predicate on the "address_line2" field.
func AddressLine2Contains(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldContains(FieldAddressLine2, v))
}

// AddressLine2HasPrefix applies the HasPrefix predicate on the "address_line2" field.
func AddressLine2HasPrefix(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldHasPrefix(FieldAddressLine2, v))
}

// AddressLine2HasSuffix applies the HasSuffix predicate on the "address_line2" field.
func AddressLine2HasSuffix(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldHasSuffix(FieldAddressLine2, v))
}

// AddressLine2IsNil applies the IsNil predicate on the "address_line2" field.
func AddressLine2IsNil() predicate.ClientUser {
	return predicate.ClientUser(sql.FieldIsNull(FieldAddressLine2))
}

// AddressLine2NotNil applies the NotNil predicate on the "address_line2" field.
func AddressLine2NotNil() predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNotNull(FieldAddressLine2))
}

// AddressLine2EqualFold applies the EqualFold predicate on the "address_line2" field.
func AddressLine2EqualFold(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEqualFold(FieldAddressLine2, v))
}

// AddressLine2ContainsFold applies the ContainsFold predicate on the "address_line2" field.
func AddressLine2ContainsFold(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldContainsFold(FieldAddressLine2, v))
}

// CityEQ applies the EQ predicate on the "city" field.
func CityEQ(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEQ(FieldCity, v))
}

// CityNEQ applies the NEQ predicate on the "city" field.
func CityNEQ(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNEQ(FieldCity, v))
}

// CityIn applies the In predicate on the "city" field.
func CityIn(vs ...string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldIn(FieldCity, vs...))
}

// CityNotIn applies the NotIn predicate on the "city" field.
func CityNotIn(vs ...string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNotIn(FieldCity, vs...))
}

// CityGT applies the GT predicate on the "city" field.
func CityGT(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldGT(FieldCity, v))
}

// CityGTE applies the GTE predicate on the "city" field.
func CityGTE(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldGTE(FieldCity, v))
}

// CityLT applies the LT predicate on the "city" field.
func CityLT(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldLT(FieldCity, v))
}

// CityLTE applies the LTE predicate on the "city" field.
func CityLTE(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldLTE(FieldCity, v))
}

// CityContains applies the Contains predicate on the "city" field.
func CityContains(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldContains(FieldCity, v))
}

// CityHasPrefix applies the HasPrefix predicate on the "city" field.
func CityHasPrefix(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldHasPrefix(FieldCity, v))
}

// CityHasSuffix applies the HasSuffix predicate on the "city" field.
func CityHasSuffix(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldHasSuffix(FieldCity, v))
}

// CityIsNil applies the IsNil predicate on the "city" field.
func CityIsNil() predicate.ClientUser {
	return predicate.ClientUser(sql.FieldIsNull(FieldCity))
}

// CityNotNil applies the NotNil predicate on the "city" field.
func CityNotNil() predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNotNull(FieldCity))
}

// CityEqualFold applies the EqualFold predicate on the "city" field.
func CityEqualFold(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEqualFold(FieldCity, v))
}

// CityContainsFold applies the ContainsFold predicate on the "city" field.
func CityContainsFold(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldContainsFold(FieldCity, v))
}

// DistrictEQ applies the EQ predicate on the "district" field.
func DistrictEQ(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEQ(FieldDistrict, v))
}

// DistrictNEQ applies the NEQ predicate on the "district" field.
func DistrictNEQ(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNEQ(FieldDistrict, v))
}

// DistrictIn applies the In predicate on the "district" field.
func DistrictIn(vs ...string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldIn(FieldDistrict, vs...))
}

// DistrictNotIn applies the NotIn predicate on the "district" field.
func DistrictNotIn(vs ...string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNotIn(FieldDistrict, vs...))
}

// DistrictGT applies the GT predicate on the "district" field.
func DistrictGT(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldGT(FieldDistrict, v))
}

// DistrictGTE applies the GTE predicate on the "district" field.
func DistrictGTE(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldGTE(FieldDistrict, v))
}

// DistrictLT applies the LT predicate on the "district" field.
func DistrictLT(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldLT(FieldDistrict, v))
}

// DistrictLTE applies the LTE predicate on the "district" field.
func DistrictLTE(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldLTE(FieldDistrict, v))
}

// DistrictContains applies the Contains predicate on the "district" field.
func DistrictContains(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldContains(FieldDistrict, v))
}

// DistrictHasPrefix applies the HasPrefix predicate on the "district" field.
func DistrictHasPrefix(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldHasPrefix(FieldDistrict, v))
}

// DistrictHasSuffix applies the HasSuffix predicate on the "district" field.
func DistrictHasSuffix(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldHasSuffix(FieldDistrict, v))
}

// DistrictIsNil applies the IsNil predicate on the "district" field.
func DistrictIsNil() predicate.ClientUser {
	return predicate.ClientUser(sql.FieldIsNull(FieldDistrict))
}

// DistrictNotNil applies the NotNil predicate on the "district" field.
func DistrictNotNil() predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNotNull(FieldDistrict))
}

// DistrictEqualFold applies the EqualFold predicate on the "district" field.
func DistrictEqualFold(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEqualFold(FieldDistrict, v))
}

// DistrictContainsFold applies the ContainsFold predicate on the "district" field.
func DistrictContainsFold(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldContainsFold(FieldDistrict, v))
}

// UpazilaEQ applies the EQ predicate on the "upazila" field.
func UpazilaEQ(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEQ(FieldUpazila, v))
}

// UpazilaNEQ applies the NEQ predicate on the "upazila" field.
func UpazilaNEQ(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNEQ(FieldUpazila, v))
}

// UpazilaIn applies the In predicate on the "upazila" field.
func UpazilaIn(vs ...string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldIn(FieldUpazila, vs...))
}

// UpazilaNotIn applies the NotIn predicate on the "upazila" field.
func UpazilaNotIn(vs ...string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNotIn(FieldUpazila, vs...))
}

// UpazilaGT applies the GT predicate on the "upazila" field.
func UpazilaGT(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldGT(FieldUpazila, v))
}

// UpazilaGTE applies the GTE predicate on the "upazila" field.
func UpazilaGTE(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldGTE(FieldUpazila, v))
}

// UpazilaLT applies the LT predicate on the "upazila" field.
func UpazilaLT(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldLT(FieldUpazila, v))
}

// UpazilaLTE applies the LTE predicate on the "upazila" field.
func UpazilaLTE(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldLTE(FieldUpazila, v))
}

// UpazilaContains applies the Contains predicate on the "upazila" field.
func UpazilaContains(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldContains(FieldUpazila, v))
}

// UpazilaHasPrefix applies the HasPrefix predicate on the "upazila" field.
func UpazilaHasPrefix(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldHasPrefix(FieldUpazila, v))
}

// UpazilaHasSuffix applies the HasSuffix predicate on the "upazila" field.
func UpazilaHasSuffix(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldHasSuffix(FieldUpazila, v))
}

// UpazilaIsNil applies the IsNil predicate on the "upazila" field.
func UpazilaIsNil() predicate.ClientUser {
	return predicate.ClientUser(sql.FieldIsNull(FieldUpazila))
}

// UpazilaNotNil applies the NotNil predicate on the "upazila" field.
func UpazilaNotNil() predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNotNull(FieldUpazila))
}

// UpazilaEqualFold applies the EqualFold predicate on the "upazila" field.
func UpazilaEqualFold(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEqualFold(FieldUpazila, v))
}

// UpazilaContainsFold applies the ContainsFold predicate on the "upazila" field.
func UpazilaContainsFold(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldContainsFold(FieldUpazila, v))
}

// UnionNameEQ applies the EQ predicate on the "union_name" field.
func UnionNameEQ(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEQ(FieldUnionName, v))
}

// UnionNameNEQ applies the NEQ predicate on the "union_name" field.
func UnionNameNEQ(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNEQ(FieldUnionName, v))
}

// UnionNameIn applies the In predicate on the "union_name" field.
func UnionNameIn(vs ...string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldIn(FieldUnionName, vs...))
}

// UnionNameNotIn applies the NotIn predicate on the "union_name" field.
func UnionNameNotIn(vs ...string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNotIn(FieldUnionName, vs...))
}

// UnionNameGT applies the GT predicate on the "union_name" field.
func UnionNameGT(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldGT(FieldUnionName, v))
}

// UnionNameGTE applies the GTE predicate on the "union_name" field.
func UnionNameGTE(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldGTE(FieldUnionName, v))
}

// UnionNameLT applies the LT predicate on the "union_name" field.
func UnionNameLT(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldLT(FieldUnionName, v))
}

// UnionNameLTE applies the LTE predicate on the "union_name" field.
func UnionNameLTE(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldLTE(FieldUnionName, v))
}

// UnionNameContains applies the Contains predicate on the "union_name" field.
func UnionNameContains(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldContains(FieldUnionName, v))
}

// UnionNameHasPrefix applies the HasPrefix predicate on the "union_name" field.
func UnionNameHasPrefix(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldHasPrefix(FieldUnionName, v))
}

// UnionNameHasSuffix applies the HasSuffix predicate on the "union_name" field.
func UnionNameHasSuffix(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldHasSuffix(FieldUnionName, v))
}

// UnionNameIsNil applies the IsNil predicate on the "union_name" field.
func UnionNameIsNil() predicate.ClientUser {
	return predicate.ClientUser(sql.FieldIsNull(FieldUnionName))
}

// UnionNameNotNil applies the NotNil predicate on the "union_name" field.
func UnionNameNotNil() predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNotNull(FieldUnionName))
}

// UnionNameEqualFold applies the EqualFold predicate on the "union_name" field.
func UnionNameEqualFold(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEqualFold(FieldUnionName, v))
}

// UnionNameContainsFold applies the ContainsFold predicate on the "union_name" field.
func UnionNameContainsFold(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldContainsFold(FieldUnionName, v))
}

// ZipEQ applies the EQ predicate on the "zip" field.
func ZipEQ(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEQ(FieldZip, v))
}

// ZipNEQ applies the NEQ predicate on the "zip" field.
func ZipNEQ(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNEQ(FieldZip, v))
}

// ZipIn applies the In predicate on the "zip" field.
func ZipIn(vs ...string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldIn(FieldZip, vs...))
}

// ZipNotIn applies the NotIn predicate on the "zip" field.
func ZipNotIn(vs ...string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNotIn(FieldZip, vs...))
}

// ZipGT applies the GT predicate on the "zip" field.
func ZipGT(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldGT(FieldZip, v))
}

// ZipGTE applies the GTE predicate on the "zip" field.
func ZipGTE(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldGTE(FieldZip, v))
}

// ZipLT applies the LT predicate on the "zip" field.
func ZipLT(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldLT(FieldZip, v))
}

// ZipLTE applies the LTE predicate on the "zip" field.
func ZipLTE(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldLTE(FieldZip, v))
}

// ZipContains applies the Contains predicate on the "zip" field.
func ZipContains(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldContains(FieldZip, v))
}

// ZipHasPrefix applies the HasPrefix predicate on the "zip" field.
func ZipHasPrefix(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldHasPrefix(FieldZip, v))
}

// ZipHasSuffix applies the HasSuffix predicate on the "zip" field.
func ZipHasSuffix(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldHasSuffix(FieldZip, v))
}

// ZipIsNil applies the IsNil predicate on the "zip" field.
func ZipIsNil() predicate.ClientUser {
	return predicate.ClientUser(sql.FieldIsNull(FieldZip))
}

// ZipNotNil applies the NotNil predicate on the "zip" field.
func ZipNotNil() predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNotNull(FieldZip))
}

// ZipEqualFold applies the EqualFold predicate on the "zip" field.
func ZipEqualFold(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEqualFold(FieldZip, v))
}

// ZipContainsFold applies the ContainsFold predicate on the "zip" field.
func ZipContainsFold(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldContainsFold(FieldZip, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNotIn(FieldStatus, vs...))
}

// PaymentDateEQ applies the EQ predicate on the "payment_date" field.
func PaymentDateEQ(v time.Time) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEQ(FieldPaymentDate, v))
}

// PaymentDateNEQ applies the NEQ predicate on the "payment_date" field.
func PaymentDateNEQ(v time.Time) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNEQ(FieldPaymentDate, v))
}

// PaymentDateIn applies the In predicate on the "payment_date" field.
func PaymentDateIn(vs ...time.Time) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldIn(FieldPaymentDate, vs...))
}

// PaymentDateNotIn applies the NotIn predicate on the "payment_date" field.
func PaymentDateNotIn(vs ...time.Time) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNotIn(FieldPaymentDate, vs...))
}

// PaymentDateGT applies the GT predicate on the "payment_date" field.
func PaymentDateGT(v time.Time) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldGT(FieldPaymentDate, v))
}

// PaymentDateGTE applies the GTE predicate on the "payment_date" field.
func PaymentDateGTE(v time.Time) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldGTE(FieldPaymentDate, v))
}

// PaymentDateLT applies the LT predicate on the "payment_date" field.
func PaymentDateLT(v time.Time) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldLT(FieldPaymentDate, v))
}

// PaymentDateLTE applies the LTE predicate on the "payment_date" field.
func PaymentDateLTE(v time.Time) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldLTE(FieldPaymentDate, v))
}

// PaymentDateIsNil applies the IsNil predicate on the "payment_date" field.
func PaymentDateIsNil() predicate.ClientUser {
	return predicate.ClientUser(sql.FieldIsNull(FieldPaymentDate))
}

// PaymentDateNotNil applies the NotNil predicate on the "payment_date" field.
func PaymentDateNotNil() predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNotNull(FieldPaymentDate))
}

// PaymentTypeEQ applies the EQ predicate on the "payment_type" field.
func PaymentTypeEQ(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEQ(FieldPaymentType, v))
}

// PaymentTypeNEQ applies the NEQ predicate on the "payment_type" field.
func PaymentTypeNEQ(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNEQ(FieldPaymentType, v))
}

// PaymentTypeIn applies the In predicate on the "payment_type" field.
func PaymentTypeIn(vs ...string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldIn(FieldPaymentType, vs...))
}

// PaymentTypeNotIn applies the NotIn predicate on the "payment_type" field.
func PaymentTypeNotIn(vs ...string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNotIn(FieldPaymentType, vs...))
}

// PaymentTypeGT applies the GT predicate on the "payment_type" field.
func PaymentTypeGT(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldGT(FieldPaymentType, v))
}

// PaymentTypeGTE applies the GTE predicate on the "payment_type" field.
func PaymentTypeGTE(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldGTE(FieldPaymentType, v))
}

// PaymentTypeLT applies the LT predicate on the "payment_type" field.
func PaymentTypeLT(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldLT(FieldPaymentType, v))
}

// PaymentTypeLTE applies the LTE predicate on the "payment_type" field.
func PaymentTypeLTE(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldLTE(FieldPaymentType, v))
}

// PaymentTypeContains applies the Contains predicate on the "payment_type" field.
func PaymentTypeContains(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldContains(FieldPaymentType, v))
}

// PaymentTypeHasPrefix applies the HasPrefix predicate on the "payment_type" field.
func PaymentTypeHasPrefix(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldHasPrefix(FieldPaymentType, v))
}

// PaymentTypeHasSuffix applies the HasSuffix predicate on the "payment_type" field.
func PaymentTypeHasSuffix(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldHasSuffix(FieldPaymentType, v))
}

// PaymentTypeIsNil applies the IsNil predicate on the "payment_type" field.
func PaymentTypeIsNil() predicate.ClientUser {
	return predicate.ClientUser(sql.FieldIsNull(FieldPaymentType))
}

// PaymentTypeNotNil applies the NotNil predicate on the "payment_type" field.
func PaymentTypeNotNil() predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNotNull(FieldPaymentType))
}

// PaymentTypeEqualFold applies the EqualFold predicate on the "payment_type" field.
func PaymentTypeEqualFold(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEqualFold(FieldPaymentType, v))
}

// PaymentTypeContainsFold applies the ContainsFold predicate on the "payment_type" field.
func PaymentTypeContainsFold(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldContainsFold(FieldPaymentType, v))
}

// AutoRenewEQ applies the EQ predicate on the "auto_renew" field.
func AutoRenewEQ(v bool) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEQ(FieldAutoRenew, v))
}

// AutoRenewNEQ applies the NEQ predicate on the "auto_renew" field.
func AutoRenewNEQ(v bool) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNEQ(FieldAutoRenew, v))
}

// CNameEQ applies the EQ predicate on the "c_name" field.
func CNameEQ(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEQ(FieldCName, v))
}

// CNameNEQ applies the NEQ predicate on the "c_name" field.
func CNameNEQ(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNEQ(FieldCName, v))
}

// CNameIn applies the In predicate on the "c_name" field.
func CNameIn(vs ...string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldIn(FieldCName, vs...))
}

// CNameNotIn applies the NotIn predicate on the "c_name" field.
func CNameNotIn(vs ...string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNotIn(FieldCName, vs...))
}

// CNameGT applies the GT predicate on the "c_name" field.
func CNameGT(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldGT(FieldCName, v))
}

// CNameGTE applies the GTE predicate on the "c_name" field.
func CNameGTE(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldGTE(FieldCName, v))
}

// CNameLT applies the LT predicate on the "c_name" field.
func CNameLT(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldLT(FieldCName, v))
}

// CNameLTE applies the LTE predicate on the "c_name" field.
func CNameLTE(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldLTE(FieldCName, v))
}

// CNameContains applies the Contains predicate on the "c_name" field.
func CNameContains(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldContains(FieldCName, v))
}

// CNameHasPrefix applies the HasPrefix predicate on the "c_name" field.
func CNameHasPrefix(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldHasPrefix(FieldCName, v))
}

// CNameHasSuffix applies the HasSuffix predicate on the "c_name" field.
func CNameHasSuffix(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldHasSuffix(FieldCName, v))
}

// CNameEqualFold applies the EqualFold predicate on the "c_name" field.
func CNameEqualFold(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEqualFold(FieldCName, v))
}

// CNameContainsFold applies the ContainsFold predicate on the "c_name" field.
func CNameContainsFold(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldContainsFold(FieldCName, v))
}

// VendorIDEQ applies the EQ predicate on the "vendor_id" field.
func VendorIDEQ(v int) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEQ(FieldVendorID, v))
}

// VendorIDNEQ applies the NEQ predicate on the "vendor_id" field.
func VendorIDNEQ(v int) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNEQ(FieldVendorID, v))
}

// VendorIDIn applies the In predicate on the "vendor_id" field.
func VendorIDIn(vs ...int) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldIn(FieldVendorID, vs...))
}

// VendorIDNotIn applies the NotIn predicate on the "vendor_id" field.
func VendorIDNotIn(vs ...int) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNotIn(FieldVendorID, vs...))
}

// VendorIDGT applies the GT predicate on the "vendor_id" field.
func VendorIDGT(v int) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldGT(FieldVendorID, v))
}

// VendorIDGTE applies the GTE predicate on the "vendor_id" field.
func VendorIDGTE(v int) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldGTE(FieldVendorID, v))
}

// VendorIDLT applies the LT predicate on the "vendor_id" field.
func VendorIDLT(v int) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldLT(FieldVendorID, v))
}

// VendorIDLTE applies the LTE predicate on the "vendor_id" field.
func VendorIDLTE(v int) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldLTE(FieldVendorID, v))
}

// PackagePoolEQ applies the EQ predicate on the "package_pool" field.
func PackagePoolEQ(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEQ(FieldPackagePool, v))
}

// PackagePoolNEQ applies the NEQ predicate on the "package_pool" field.
func PackagePoolNEQ(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNEQ(FieldPackagePool, v))
}

// PackagePoolIn applies the In predicate on the "package_pool" field.
func PackagePoolIn(vs ...string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldIn(FieldPackagePool, vs...))
}

// PackagePoolNotIn applies the NotIn predicate on the "package_pool" field.
func PackagePoolNotIn(vs ...string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNotIn(FieldPackagePool, vs...))
}

// PackagePoolGT applies the GT predicate on the "package_pool" field.
func PackagePoolGT(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldGT(FieldPackagePool, v))
}

// PackagePoolGTE applies the GTE predicate on the "package_pool" field.
func PackagePoolGTE(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldGTE(FieldPackagePool, v))
}

// PackagePoolLT applies the LT predicate on the "package_pool" field.
func PackagePoolLT(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldLT(FieldPackagePool, v))
}

// PackagePoolLTE applies the LTE predicate on the "package_pool" field.
func PackagePoolLTE(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldLTE(FieldPackagePool, v))
}

// PackagePoolContains applies the Contains predicate on the "package_pool" field.
func PackagePoolContains(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldContains(FieldPackagePool, v))
}

// PackagePoolHasPrefix applies the HasPrefix predicate on the "package_pool" field.
func PackagePoolHasPrefix(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldHasPrefix(FieldPackagePool, v))
}

// PackagePoolHasSuffix applies the HasSuffix predicate on the "package_pool" field.
func PackagePoolHasSuffix(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldHasSuffix(FieldPackagePool, v))
}

// PackagePoolIsNil applies the IsNil predicate on the "package_pool" field.
func PackagePoolIsNil() predicate.ClientUser {
	return predicate.ClientUser(sql.FieldIsNull(FieldPackagePool))
}

// PackagePoolNotNil applies the NotNil predicate on the "package_pool" field.
func PackagePoolNotNil() predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNotNull(FieldPackagePool))
}

// PackagePoolEqualFold applies the EqualFold predicate on the "package_pool" field.
func PackagePoolEqualFold(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEqualFold(FieldPackagePool, v))
}

// PackagePoolContainsFold applies the ContainsFold predicate on the "package_pool" field.
func PackagePoolContainsFold(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldContainsFold(FieldPackagePool, v))
}

// UserProfileEQ applies the EQ predicate on the "user_profile" field.
func UserProfileEQ(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEQ(FieldUserProfile, v))
}

// UserProfileNEQ applies the NEQ predicate on the "user_profile" field.
func UserProfileNEQ(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNEQ(FieldUserProfile, v))
}

// UserProfileIn applies the In predicate on the "user_profile" field.
func UserProfileIn(vs ...string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldIn(FieldUserProfile, vs...))
}

// UserProfileNotIn applies the NotIn predicate on the "user_profile" field.
func UserProfileNotIn(vs ...string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNotIn(FieldUserProfile, vs...))
}

// UserProfileGT applies the GT predicate on the "user_profile" field.
func UserProfileGT(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldGT(FieldUserProfile, v))
}

// UserProfileGTE applies the GTE predicate on the "user_profile" field.
func UserProfileGTE(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldGTE(FieldUserProfile, v))
}

// UserProfileLT applies the LT predicate on the "user_profile" field.
func UserProfileLT(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldLT(FieldUserProfile, v))
}

// UserProfileLTE applies the LTE predicate on the "user_profile" field.
func UserProfileLTE(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldLTE(FieldUserProfile, v))
}

// UserProfileContains applies the Contains predicate on the "user_profile" field.
func UserProfileContains(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldContains(FieldUserProfile, v))
}

// UserProfileHasPrefix applies the HasPrefix predicate on the "user_profile" field.
func UserProfileHasPrefix(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldHasPrefix(FieldUserProfile, v))
}

// UserProfileHasSuffix applies the HasSuffix predicate on the "user_profile" field.
func UserProfileHasSuffix(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldHasSuffix(FieldUserProfile, v))
}

// UserProfileIsNil applies the IsNil predicate on the "user_profile" field.
func UserProfileIsNil() predicate.ClientUser {
	return predicate.ClientUser(sql.FieldIsNull(FieldUserProfile))
}

// UserProfileNotNil applies the NotNil predicate on the "user_profile" field.
func UserProfileNotNil() predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNotNull(FieldUserProfile))
}

// UserProfileEqualFold applies the EqualFold predicate on the "user_profile" field.
func UserProfileEqualFold(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEqualFold(FieldUserProfile, v))
}

// UserProfileContainsFold applies the ContainsFold predicate on the "user_profile" field.
func UserProfileContainsFold(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldContainsFold(FieldUserProfile, v))
}

// NextUserProfileEQ applies the EQ predicate on the "next_user_profile" field.
func NextUserProfileEQ(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEQ(FieldNextUserProfile, v))
}

// NextUserProfileNEQ applies the NEQ predicate on the "next_user_profile" field.
func NextUserProfileNEQ(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNEQ(FieldNextUserProfile, v))
}

// NextUserProfileIn applies the In predicate on the "next_user_profile" field.
func NextUserProfileIn(vs ...string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldIn(FieldNextUserProfile, vs...))
}

// NextUserProfileNotIn applies the NotIn predicate on the "next_user_profile" field.
func NextUserProfileNotIn(vs ...string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNotIn(FieldNextUserProfile, vs...))
}

// NextUserProfileGT applies the GT predicate on the "next_user_profile" field.
func NextUserProfileGT(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldGT(FieldNextUserProfile, v))
}

// NextUserProfileGTE applies the GTE predicate on the "next_user_profile" field.
func NextUserProfileGTE(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldGTE(FieldNextUserProfile, v))
}

// NextUserProfileLT applies the LT predicate on the "next_user_profile" field.
func NextUserProfileLT(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldLT(FieldNextUserProfile, v))
}

// NextUserProfileLTE applies the LTE predicate on the "next_user_profile" field.
func NextUserProfileLTE(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldLTE(FieldNextUserProfile, v))
}

// NextUserProfileContains applies the Contains predicate on the "next_user_profile" field.
func NextUserProfileContains(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldContains(FieldNextUserProfile, v))
}

// NextUserProfileHasPrefix applies the HasPrefix predicate on the "next_user_profile" field.
func NextUserProfileHasPrefix(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldHasPrefix(FieldNextUserProfile, v))
}

// NextUserProfileHasSuffix applies the HasSuffix predicate on the "next_user_profile" field.
func NextUserProfileHasSuffix(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldHasSuffix(FieldNextUserProfile, v))
}

// NextUserProfileIsNil applies the IsNil predicate on the "next_user_profile" field.
func NextUserProfileIsNil() predicate.ClientUser {
	return predicate.ClientUser(sql.FieldIsNull(FieldNextUserProfile))
}

// NextUserProfileNotNil applies the NotNil predicate on the "next_user_profile" field.
func NextUserProfileNotNil() predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNotNull(FieldNextUserProfile))
}

// NextUserProfileEqualFold applies the EqualFold predicate on the "next_user_profile" field.
func NextUserProfileEqualFold(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEqualFold(FieldNextUserProfile, v))
}

// NextUserProfileContainsFold applies the ContainsFold predicate on the "next_user_profile" field.
func NextUserProfileContainsFold(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldContainsFold(FieldNextUserProfile, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldContainsFold(FieldCreatedBy, v))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByContains applies the Contains predicate on the "updated_by" field.
func UpdatedByContains(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldContains(FieldUpdatedBy, v))
}

// UpdatedByHasPrefix applies the HasPrefix predicate on the "updated_by" field.
func UpdatedByHasPrefix(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldHasPrefix(FieldUpdatedBy, v))
}

// UpdatedByHasSuffix applies the HasSuffix predicate on the "updated_by" field.
func UpdatedByHasSuffix(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldHasSuffix(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.ClientUser {
	return predicate.ClientUser(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNotNull(FieldUpdatedBy))
}

// UpdatedByEqualFold applies the EqualFold predicate on the "updated_by" field.
func UpdatedByEqualFold(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEqualFold(FieldUpdatedBy, v))
}

// UpdatedByContainsFold applies the ContainsFold predicate on the "updated_by" field.
func UpdatedByContainsFold(v string) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldContainsFold(FieldUpdatedBy, v))
}

// CreatedDateEQ applies the EQ predicate on the "created_date" field.
func CreatedDateEQ(v time.Time) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEQ(FieldCreatedDate, v))
}

// CreatedDateNEQ applies the NEQ predicate on the "created_date" field.
func CreatedDateNEQ(v time.Time) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNEQ(FieldCreatedDate, v))
}

// CreatedDateIn applies the In predicate on the "created_date" field.
func CreatedDateIn(vs ...time.Time) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldIn(FieldCreatedDate, vs...))
}

// CreatedDateNotIn applies the NotIn predicate on the "created_date" field.
func CreatedDateNotIn(vs ...time.Time) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNotIn(FieldCreatedDate, vs...))
}

// CreatedDateGT applies the GT predicate on the "created_date" field.
func CreatedDateGT(v time.Time) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldGT(FieldCreatedDate, v))
}

// CreatedDateGTE applies the GTE predicate on the "created_date" field.
func CreatedDateGTE(v time.Time) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldGTE(FieldCreatedDate, v))
}

// CreatedDateLT applies the LT predicate on the "created_date" field.
func CreatedDateLT(v time.Time) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldLT(FieldCreatedDate, v))
}

// CreatedDateLTE applies the LTE predicate on the "created_date" field.
func CreatedDateLTE(v time.Time) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldLTE(FieldCreatedDate, v))
}

// UpdatedDateEQ applies the EQ predicate on the "updated_date" field.
func UpdatedDateEQ(v time.Time) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldEQ(FieldUpdatedDate, v))
}

// UpdatedDateNEQ applies the NEQ predicate on the "updated_date" field.
func UpdatedDateNEQ(v time.Time) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNEQ(FieldUpdatedDate, v))
}

// UpdatedDateIn applies the In predicate on the "updated_date" field.
func UpdatedDateIn(vs ...time.Time) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldIn(FieldUpdatedDate, vs...))
}

// UpdatedDateNotIn applies the NotIn predicate on the "updated_date" field.
func UpdatedDateNotIn(vs ...time.Time) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNotIn(FieldUpdatedDate, vs...))
}

// UpdatedDateGT applies the GT predicate on the "updated_date" field.
func UpdatedDateGT(v time.Time) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldGT(FieldUpdatedDate, v))
}

// UpdatedDateGTE applies the GTE predicate on the "updated_date" field.
func UpdatedDateGTE(v time.Time) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldGTE(FieldUpdatedDate, v))
}

// UpdatedDateLT applies the LT predicate on the "updated_date" field.
func UpdatedDateLT(v time.Time) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldLT(FieldUpdatedDate, v))
}

// UpdatedDateLTE applies the LTE predicate on the "updated_date" field.
func UpdatedDateLTE(v time.Time) predicate.ClientUser {
	return predicate.ClientUser(sql.FieldLTE(FieldUpdatedDate, v))
}

// UpdatedDateIsNil applies the IsNil predicate on the "updated_date" field.
func UpdatedDateIsNil() predicate.ClientUser {
	return predicate.ClientUser(sql.FieldIsNull(FieldUpdatedDate))
}

// UpdatedDateNotNil applies the NotNil predicate on the "updated_date" field.
func UpdatedDateNotNil() predicate.ClientUser {
	return predicate.ClientUser(sql.FieldNotNull(FieldUpdatedDate))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ClientUser) predicate.ClientUser {
	return predicate.ClientUser(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ClientUser) predicate.ClientUser {
	return predicate.ClientUser(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ClientUser) predicate.ClientUser {
	return predicate.ClientUser(sql.NotPredicates(p))
}
