// Code generated by ent, DO NOT EDIT.

package clienttxn

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the clienttxn type in the database.
	Label = "client_txn"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTransactionRef holds the string denoting the transaction_ref field in the database.
	FieldTransactionRef = "transaction_ref"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "balance"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldTotalBalance holds the string denoting the total_balance field in the database.
	FieldTotalBalance = "total_balance"
	// FieldPaymentMethod holds the string denoting the payment_method field in the database.
	FieldPaymentMethod = "payment_method"
	// FieldClientUsername holds the string denoting the client_username field in the database.
	FieldClientUsername = "client_username"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldTransactionDate holds the string denoting the transaction_date field in the database.
	FieldTransactionDate = "transaction_date"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// Table holds the table name of the clienttxn in the database.
	Table = "client_txn"
)

// Columns holds all SQL columns for clienttxn fields.
var Columns = []string{
	FieldID,
	FieldTransactionRef,
	FieldAmount,
	FieldType,
	FieldStatus,
	FieldTotalBalance,
	FieldPaymentMethod,
	FieldClientUsername,
	FieldDescription,
	FieldTransactionDate,
	FieldCreatedBy,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TransactionRefValidator is a validator for the "transaction_ref" field. It is called by the builders before save.
	TransactionRefValidator func(string) error
	// DefaultAmount holds the default value on creation for the "amount" field.
	DefaultAmount float64
	// DefaultTotalBalance holds the default value on creation for the "total_balance" field.
	DefaultTotalBalance float64
	// ClientUsernameValidator is a validator for the "client_username" field. It is called by the builders before save.
	ClientUsernameValidator func(string) error
	// DefaultTransactionDate holds the default value on creation for the "transaction_date" field.
	DefaultTransactionDate func() time.Time
	// CreatedByValidator is a validator for the "created_by" field. It is called by the builders before save.
	CreatedByValidator func(string) error
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(int) error
)

// Type defines the type for the "type" enum field.
type Type string

// Type values.
const (
	TypeACTIVE            Type = "ACTIVE"
	TypeRENEWAL           Type = "RENEWAL"
	TypeREFUND            Type = "REFUND"
	TypeTRANSFER_REFUND   Type = "TRANSFER_REFUND"
	TypeTRANSFER_RECEIVED Type = "TRANSFER_RECEIVED"
	TypeAUTO_RENEWAL      Type = "AUTO_RENEWAL"
	TypePACKAGE_MIGRATION Type = "PACKAGE_MIGRATION"
	TypeADVANCE_PAYMENT   Type = "ADVANCE_PAYMENT"
)

func (_type Type) String() string {
	return string(_type)
}

// TypeValidator is a validator for the "type" field enum values. It is called by the builders before save.
func TypeValidator(_type Type) error {
	switch _type {
	case TypeACTIVE, TypeRENEWAL, TypeREFUND, TypeTRANSFER_REFUND, TypeTRANSFER_RECEIVED, TypeAUTO_RENEWAL, TypePACKAGE_MIGRATION, TypeADVANCE_PAYMENT:
		return nil
	default:
		return fmt.Errorf("clienttxn: invalid enum value for type field: %q", _type)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusCompleted is the default value of the Status enum.
const DefaultStatus = StatusCompleted

// Status values.
const (
	StatusPending   Status = "pending"
	StatusCompleted Status = "completed"
	StatusFailed    Status = "failed"
	StatusReversed  Status = "reversed"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusPending, StatusCompleted, StatusFailed, StatusReversed:
		return nil
	default:
		return fmt.Errorf("clienttxn: invalid enum value for status field: %q", s)
	}
}

// PaymentMethod defines the type for the "payment_method" enum field.
type PaymentMethod string

// PaymentMethod values.
const (
	PaymentMethodVendorBalance     PaymentMethod = "vendor_balance"
	PaymentMethodClientBalance     PaymentMethod = "client_balance"
	PaymentMethodCash              PaymentMethod = "cash"
	PaymentMethodBankTransfer      PaymentMethod = "bank_transfer"
	PaymentMethodMobileBanking     PaymentMethod = "mobile_banking"
	PaymentMethodCard              PaymentMethod = "card"
	PaymentMethodGatewaySslcommerz PaymentMethod = "gateway_sslcommerz"
	PaymentMethodGatewayBkash      PaymentMethod = "gateway_bkash"
	PaymentMethodGatewayNagad      PaymentMethod = "gateway_nagad"
	PaymentMethodGatewayStripe     PaymentMethod = "gateway_stripe"
	PaymentMethodGatewayPaypal     PaymentMethod = "gateway_paypal"
	PaymentMethodFree              PaymentMethod = "free"
	PaymentMethodOther             PaymentMethod = "other"
)

func (pm PaymentMethod) String() string {
	return string(pm)
}

// PaymentMethodValidator is a validator for the "payment_method" field enum values. It is called by the builders before save.
func PaymentMethodValidator(pm PaymentMethod) error {
	switch pm {
	case PaymentMethodVendorBalance, PaymentMethodClientBalance, PaymentMethodCash, PaymentMethodBankTransfer, PaymentMethodMobileBanking, PaymentMethodCard, PaymentMethodGatewaySslcommerz, PaymentMethodGatewayBkash, PaymentMethodGatewayNagad, PaymentMethodGatewayStripe, PaymentMethodGatewayPaypal, PaymentMethodFree, PaymentMethodOther:
		return nil
	default:
		return fmt.Errorf("clienttxn: invalid enum value for payment_method field: %q", pm)
	}
}

// OrderOption defines the ordering options for the ClientTxn queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTransactionRef orders the results by the transaction_ref field.
func ByTransactionRef(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTransactionRef, opts...).ToFunc()
}

// ByAmount orders the results by the amount field.
func ByAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmount, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByTotalBalance orders the results by the total_balance field.
func ByTotalBalance(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalBalance, opts...).ToFunc()
}

// ByPaymentMethod orders the results by the payment_method field.
func ByPaymentMethod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPaymentMethod, opts...).ToFunc()
}

// ByClientUsername orders the results by the client_username field.
func ByClientUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClientUsername, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByTransactionDate orders the results by the transaction_date field.
func ByTransactionDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTransactionDate, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}
