// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ClientTxnColumns holds the columns for the "client_txn" table.
	ClientTxnColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "transaction_ref", Type: field.TypeString, Unique: true, Size: 64},
		{Name: "balance", Type: field.TypeFloat64, Default: 0},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"ACTIVE", "RENEWAL", "REFUND", "TRANSFER_REFUND", "TRANSFER_RECEIVED", "AUTO_RENEWAL", "PACKAGE_MIGRATION", "ADVANCE_PAYMENT"}},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending", "completed", "failed", "reversed"}, Default: "completed"},
		{Name: "total_balance", Type: field.TypeFloat64, Default: 0},
		{Name: "payment_method", Type: field.TypeEnum, Nullable: true, Enums: []string{"vendor_balance", "client_balance", "cash", "bank_transfer", "mobile_banking", "card", "gateway_sslcommerz", "gateway_bkash", "gateway_nagad", "gateway_stripe", "gateway_paypal", "free", "other"}},
		{Name: "client_username", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "transaction_date", Type: field.TypeTime},
		{Name: "created_by", Type: field.TypeString, Size: 255},
	}
	// ClientTxnTable holds the schema information for the "client_txn" table.
	ClientTxnTable = &schema.Table{
		Name:       "client_txn",
		Columns:    ClientTxnColumns,
		PrimaryKey: []*schema.Column{ClientTxnColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "clienttxn_transaction_ref",
				Unique:  false,
				Columns: []*schema.Column{ClientTxnColumns[1]},
			},
			{
				Name:    "clienttxn_client_username",
				Unique:  false,
				Columns: []*schema.Column{ClientTxnColumns[7]},
			},
			{
				Name:    "clienttxn_status",
				Unique:  false,
				Columns: []*schema.Column{ClientTxnColumns[4]},
			},
			{
				Name:    "clienttxn_type",
				Unique:  false,
				Columns: []*schema.Column{ClientTxnColumns[3]},
			},
			{
				Name:    "clienttxn_transaction_date",
				Unique:  false,
				Columns: []*schema.Column{ClientTxnColumns[9]},
			},
		},
	}
	// ClientsColumns holds the columns for the "clients" table.
	ClientsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Size: 255},
		{Name: "username", Type: field.TypeString, Unique: true, Size: 255},
		{Name: "password", Type: field.TypeString, Size: 255},
		{Name: "mobile_number", Type: field.TypeString, Size: 255},
		{Name: "email", Type: field.TypeString, Size: 255},
		{Name: "photo", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "balance", Type: field.TypeFloat64, Default: 0},
		{Name: "address_line1", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "address_line2", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "city", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "district", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "upazila", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "union_name", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "zip", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "inactive"}, Default: "inactive"},
		{Name: "payment_date", Type: field.TypeTime, Nullable: true},
		{Name: "payment_type", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "auto_renew", Type: field.TypeBool, Default: true},
		{Name: "c_name", Type: field.TypeString, Size: 32},
		{Name: "vendor_id", Type: field.TypeInt},
		{Name: "package_pool", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "user_profile", Type: field.TypeString, Nullable: true, Size: 64},
		{Name: "next_user_profile", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "created_by", Type: field.TypeString, Size: 255},
		{Name: "updated_by", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "created_date", Type: field.TypeTime},
		{Name: "updated_date", Type: field.TypeTime, Nullable: true},
	}
	// ClientsTable holds the schema information for the "clients" table.
	ClientsTable = &schema.Table{
		Name:       "clients",
		Columns:    ClientsColumns,
		PrimaryKey: []*schema.Column{ClientsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "clientuser_mobile_number",
				Unique:  false,
				Columns: []*schema.Column{ClientsColumns[4]},
			},
			{
				Name:    "clientuser_email",
				Unique:  false,
				Columns: []*schema.Column{ClientsColumns[5]},
			},
			{
				Name:    "clientuser_c_name",
				Unique:  false,
				Columns: []*schema.Column{ClientsColumns[20]},
			},
			{
				Name:    "clientuser_vendor_id",
				Unique:  false,
				Columns: []*schema.Column{ClientsColumns[21]},
			},
			{
				Name:    "clientuser_package_pool",
				Unique:  false,
				Columns: []*schema.Column{ClientsColumns[22]},
			},
			{
				Name:    "clientuser_user_profile",
				Unique:  false,
				Columns: []*schema.Column{ClientsColumns[23]},
			},
			{
				Name:    "clientuser_next_user_profile",
				Unique:  false,
				Columns: []*schema.Column{ClientsColumns[24]},
			},
			{
				Name:    "clientuser_auto_renew",
				Unique:  false,
				Columns: []*schema.Column{ClientsColumns[19]},
			},
			{
				Name:    "clientuser_created_date",
				Unique:  false,
				Columns: []*schema.Column{ClientsColumns[27]},
			},
			{
				Name:    "clientuser_created_by",
				Unique:  false,
				Columns: []*schema.Column{ClientsColumns[25]},
			},
			{
				Name:    "clientuser_status",
				Unique:  false,
				Columns: []*schema.Column{ClientsColumns[16]},
			},
			{
				Name:    "clientuser_name",
				Unique:  false,
				Columns: []*schema.Column{ClientsColumns[1]},
			},
			{
				Name:    "clientuser_balance",
				Unique:  false,
				Columns: []*schema.Column{ClientsColumns[8]},
			},
			{
				Name:    "clientuser_c_name_status_created_date",
				Unique:  false,
				Columns: []*schema.Column{ClientsColumns[20], ClientsColumns[16], ClientsColumns[27]},
			},
			{
				Name:    "clientuser_c_name_vendor_id_status_created_date",
				Unique:  false,
				Columns: []*schema.Column{ClientsColumns[20], ClientsColumns[21], ClientsColumns[16], ClientsColumns[27]},
			},
			{
				Name:    "clientuser_package_pool_status_created_date",
				Unique:  false,
				Columns: []*schema.Column{ClientsColumns[22], ClientsColumns[16], ClientsColumns[27]},
			},
			{
				Name:    "clientuser_auto_renew_status_c_name_created_date",
				Unique:  false,
				Columns: []*schema.Column{ClientsColumns[19], ClientsColumns[16], ClientsColumns[20], ClientsColumns[27]},
			},
			{
				Name:    "clientuser_vendor_id_package_pool_status",
				Unique:  false,
				Columns: []*schema.Column{ClientsColumns[21], ClientsColumns[22], ClientsColumns[16]},
			},
			{
				Name:    "clientuser_c_name_vendor_id_status",
				Unique:  false,
				Columns: []*schema.Column{ClientsColumns[20], ClientsColumns[21], ClientsColumns[16]},
			},
			{
				Name:    "clientuser_updated_date_status",
				Unique:  false,
				Columns: []*schema.Column{ClientsColumns[28], ClientsColumns[16]},
			},
		},
	}
	// EmailSubscriptionsColumns holds the columns for the "email_subscriptions" table.
	EmailSubscriptionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "verified", Type: field.TypeBool, Default: false},
		{Name: "confirmation_code", Type: field.TypeString, Unique: true},
		{Name: "latitude", Type: field.TypeFloat64, Nullable: true},
		{Name: "longitude", Type: field.TypeFloat64, Nullable: true},
	}
	// EmailSubscriptionsTable holds the schema information for the "email_subscriptions" table.
	EmailSubscriptionsTable = &schema.Table{
		Name:       "email_subscriptions",
		Columns:    EmailSubscriptionsColumns,
		PrimaryKey: []*schema.Column{EmailSubscriptionsColumns[0]},
	}
	// EmailSubscriptionTypesColumns holds the columns for the "email_subscription_types" table.
	EmailSubscriptionTypesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "name", Type: field.TypeEnum, Enums: []string{"email_newsletter", "launch_announcement"}},
		{Name: "active", Type: field.TypeBool, Default: true},
	}
	// EmailSubscriptionTypesTable holds the schema information for the "email_subscription_types" table.
	EmailSubscriptionTypesTable = &schema.Table{
		Name:       "email_subscription_types",
		Columns:    EmailSubscriptionTypesColumns,
		PrimaryKey: []*schema.Column{EmailSubscriptionTypesColumns[0]},
	}
	// EmojisColumns holds the columns for the "emojis" table.
	EmojisColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "unified_code", Type: field.TypeString},
		{Name: "shortcode", Type: field.TypeString},
	}
	// EmojisTable holds the schema information for the "emojis" table.
	EmojisTable = &schema.Table{
		Name:       "emojis",
		Columns:    EmojisColumns,
		PrimaryKey: []*schema.Column{EmojisColumns[0]},
	}
	// FcmSubscriptionsColumns holds the columns for the "fcm_subscriptions" table.
	FcmSubscriptionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "token", Type: field.TypeString},
		{Name: "profile_id", Type: field.TypeInt},
	}
	// FcmSubscriptionsTable holds the schema information for the "fcm_subscriptions" table.
	FcmSubscriptionsTable = &schema.Table{
		Name:       "fcm_subscriptions",
		Columns:    FcmSubscriptionsColumns,
		PrimaryKey: []*schema.Column{FcmSubscriptionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "fcm_subscriptions_profiles_fcm_push_subscriptions",
				Columns:    []*schema.Column{FcmSubscriptionsColumns[4]},
				RefColumns: []*schema.Column{ProfilesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "fcmsubscriptions_token_profile_id",
				Unique:  true,
				Columns: []*schema.Column{FcmSubscriptionsColumns[3], FcmSubscriptionsColumns[4]},
			},
		},
	}
	// FileStoragesColumns holds the columns for the "file_storages" table.
	FileStoragesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "bucket_name", Type: field.TypeString},
		{Name: "object_key", Type: field.TypeString},
		{Name: "original_file_name", Type: field.TypeString, Nullable: true},
		{Name: "file_size", Type: field.TypeInt64, Nullable: true},
		{Name: "content_type", Type: field.TypeString, Nullable: true},
		{Name: "file_hash", Type: field.TypeString, Nullable: true},
	}
	// FileStoragesTable holds the schema information for the "file_storages" table.
	FileStoragesTable = &schema.Table{
		Name:       "file_storages",
		Columns:    FileStoragesColumns,
		PrimaryKey: []*schema.Column{FileStoragesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "filestorage_bucket_name_object_key",
				Unique:  true,
				Columns: []*schema.Column{FileStoragesColumns[3], FileStoragesColumns[4]},
			},
		},
	}
	// ImagesColumns holds the columns for the "images" table.
	ImagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"profile_photo", "profile_gallery"}},
		{Name: "profile_photos", Type: field.TypeInt, Nullable: true},
	}
	// ImagesTable holds the schema information for the "images" table.
	ImagesTable = &schema.Table{
		Name:       "images",
		Columns:    ImagesColumns,
		PrimaryKey: []*schema.Column{ImagesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "images_profiles_photos",
				Columns:    []*schema.Column{ImagesColumns[4]},
				RefColumns: []*schema.Column{ProfilesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// ImageSizesColumns holds the columns for the "image_sizes" table.
	ImageSizesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "size", Type: field.TypeEnum, Enums: []string{"thumbnail", "preview", "full"}},
		{Name: "width", Type: field.TypeInt},
		{Name: "height", Type: field.TypeInt},
		{Name: "image_sizes", Type: field.TypeInt, Nullable: true},
		{Name: "image_size_file", Type: field.TypeInt},
	}
	// ImageSizesTable holds the schema information for the "image_sizes" table.
	ImageSizesTable = &schema.Table{
		Name:       "image_sizes",
		Columns:    ImageSizesColumns,
		PrimaryKey: []*schema.Column{ImageSizesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "image_sizes_images_sizes",
				Columns:    []*schema.Column{ImageSizesColumns[6]},
				RefColumns: []*schema.Column{ImagesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "image_sizes_file_storages_file",
				Columns:    []*schema.Column{ImageSizesColumns[7]},
				RefColumns: []*schema.Column{FileStoragesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// InvitationsColumns holds the columns for the "invitations" table.
	InvitationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "invitee_name", Type: field.TypeString},
		{Name: "confirmation_code", Type: field.TypeString, Unique: true},
		{Name: "profile_invitations", Type: field.TypeInt},
	}
	// InvitationsTable holds the schema information for the "invitations" table.
	InvitationsTable = &schema.Table{
		Name:       "invitations",
		Columns:    InvitationsColumns,
		PrimaryKey: []*schema.Column{InvitationsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "invitations_profiles_invitations",
				Columns:    []*schema.Column{InvitationsColumns[5]},
				RefColumns: []*schema.Column{ProfilesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// LastSeenOnlinesColumns holds the columns for the "last_seen_onlines" table.
	LastSeenOnlinesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "seen_at", Type: field.TypeTime},
		{Name: "user_last_seen_at", Type: field.TypeInt},
	}
	// LastSeenOnlinesTable holds the schema information for the "last_seen_onlines" table.
	LastSeenOnlinesTable = &schema.Table{
		Name:       "last_seen_onlines",
		Columns:    LastSeenOnlinesColumns,
		PrimaryKey: []*schema.Column{LastSeenOnlinesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "last_seen_onlines_users_last_seen_at",
				Columns:    []*schema.Column{LastSeenOnlinesColumns[2]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// MonthlySubscriptionsColumns holds the columns for the "monthly_subscriptions" table.
	MonthlySubscriptionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "product", Type: field.TypeEnum, Enums: []string{"free", "pro"}, Default: "free"},
		{Name: "is_active", Type: field.TypeBool, Default: false},
		{Name: "paid", Type: field.TypeBool, Default: false},
		{Name: "is_trial", Type: field.TypeBool, Default: true},
		{Name: "started_at", Type: field.TypeTime, Nullable: true},
		{Name: "expired_on", Type: field.TypeTime, Nullable: true},
		{Name: "cancelled_at", Type: field.TypeTime, Nullable: true},
		{Name: "paying_profile_id", Type: field.TypeInt},
	}
	// MonthlySubscriptionsTable holds the schema information for the "monthly_subscriptions" table.
	MonthlySubscriptionsTable = &schema.Table{
		Name:       "monthly_subscriptions",
		Columns:    MonthlySubscriptionsColumns,
		PrimaryKey: []*schema.Column{MonthlySubscriptionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "monthly_subscriptions_profiles_payer",
				Columns:    []*schema.Column{MonthlySubscriptionsColumns[10]},
				RefColumns: []*schema.Column{ProfilesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "monthlysubscription_paying_profile_id_is_active",
				Unique:  true,
				Columns: []*schema.Column{MonthlySubscriptionsColumns[10], MonthlySubscriptionsColumns[4]},
			},
		},
	}
	// NotificationsColumns holds the columns for the "notifications" table.
	NotificationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"new_private_message", "connection_engaged_with_question", "increment_num_unseen_msg", "decrement_num_unseen_msg", "update_num_notifs", "platform_update", "payment_failed"}},
		{Name: "title", Type: field.TypeString, Default: ""},
		{Name: "text", Type: field.TypeString},
		{Name: "link", Type: field.TypeString, Nullable: true},
		{Name: "read", Type: field.TypeBool, Default: false},
		{Name: "read_at", Type: field.TypeTime, Nullable: true},
		{Name: "profile_id_who_caused_notification", Type: field.TypeInt, Nullable: true},
		{Name: "resource_id_tied_to_notif", Type: field.TypeInt, Nullable: true},
		{Name: "read_in_notifications_center", Type: field.TypeBool, Nullable: true},
		{Name: "profile_notifications", Type: field.TypeInt, Nullable: true},
	}
	// NotificationsTable holds the schema information for the "notifications" table.
	NotificationsTable = &schema.Table{
		Name:       "notifications",
		Columns:    NotificationsColumns,
		PrimaryKey: []*schema.Column{NotificationsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "notifications_profiles_notifications",
				Columns:    []*schema.Column{NotificationsColumns[12]},
				RefColumns: []*schema.Column{ProfilesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// NotificationPermissionsColumns holds the columns for the "notification_permissions" table.
	NotificationPermissionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "permission", Type: field.TypeEnum, Enums: []string{"partner_activity"}},
		{Name: "platform", Type: field.TypeEnum, Enums: []string{"push", "fcm_push", "email", "sms"}},
		{Name: "token", Type: field.TypeString},
		{Name: "profile_id", Type: field.TypeInt},
	}
	// NotificationPermissionsTable holds the schema information for the "notification_permissions" table.
	NotificationPermissionsTable = &schema.Table{
		Name:       "notification_permissions",
		Columns:    NotificationPermissionsColumns,
		PrimaryKey: []*schema.Column{NotificationPermissionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "notification_permissions_profiles_notification_permissions",
				Columns:    []*schema.Column{NotificationPermissionsColumns[6]},
				RefColumns: []*schema.Column{ProfilesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "notificationpermission_profile_id_permission_platform",
				Unique:  true,
				Columns: []*schema.Column{NotificationPermissionsColumns[6], NotificationPermissionsColumns[3], NotificationPermissionsColumns[4]},
			},
		},
	}
	// NotificationTimesColumns holds the columns for the "notification_times" table.
	NotificationTimesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"new_private_message", "connection_engaged_with_question", "increment_num_unseen_msg", "decrement_num_unseen_msg", "update_num_notifs", "platform_update", "payment_failed"}},
		{Name: "send_minute", Type: field.TypeInt},
		{Name: "profile_id", Type: field.TypeInt},
	}
	// NotificationTimesTable holds the schema information for the "notification_times" table.
	NotificationTimesTable = &schema.Table{
		Name:       "notification_times",
		Columns:    NotificationTimesColumns,
		PrimaryKey: []*schema.Column{NotificationTimesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "notification_times_profiles_notification_times",
				Columns:    []*schema.Column{NotificationTimesColumns[5]},
				RefColumns: []*schema.Column{ProfilesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "notificationtime_profile_id_type",
				Unique:  true,
				Columns: []*schema.Column{NotificationTimesColumns[5], NotificationTimesColumns[3]},
			},
		},
	}
	// PackagesColumns holds the columns for the "packages" table.
	PackagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Size: 255},
		{Name: "pool_name", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "profile_name", Type: field.TypeString, Size: 100},
		{Name: "price", Type: field.TypeFloat64, Default: 0},
		{Name: "currency", Type: field.TypeString, Size: 3, Default: "BDT"},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "created_date", Type: field.TypeTime},
	}
	// PackagesTable holds the schema information for the "packages" table.
	PackagesTable = &schema.Table{
		Name:       "packages",
		Columns:    PackagesColumns,
		PrimaryKey: []*schema.Column{PackagesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "packageplan_name",
				Unique:  false,
				Columns: []*schema.Column{PackagesColumns[1]},
			},
			{
				Name:    "packageplan_profile_name",
				Unique:  false,
				Columns: []*schema.Column{PackagesColumns[3]},
			},
			{
				Name:    "packageplan_is_active",
				Unique:  false,
				Columns: []*schema.Column{PackagesColumns[6]},
			},
		},
	}
	// PhoneVerificationCodesColumns holds the columns for the "phone_verification_codes" table.
	PhoneVerificationCodesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "code", Type: field.TypeString},
		{Name: "profile_id", Type: field.TypeInt},
	}
	// PhoneVerificationCodesTable holds the schema information for the "phone_verification_codes" table.
	PhoneVerificationCodesTable = &schema.Table{
		Name:       "phone_verification_codes",
		Columns:    PhoneVerificationCodesColumns,
		PrimaryKey: []*schema.Column{PhoneVerificationCodesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "phone_verification_codes_profiles_phone_verification_code",
				Columns:    []*schema.Column{PhoneVerificationCodesColumns[4]},
				RefColumns: []*schema.Column{ProfilesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "phoneverificationcode_code_profile_id",
				Unique:  true,
				Columns: []*schema.Column{PhoneVerificationCodesColumns[3], PhoneVerificationCodesColumns[4]},
			},
		},
	}
	// ProfilesColumns holds the columns for the "profiles" table.
	ProfilesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "bio", Type: field.TypeString, Nullable: true},
		{Name: "birthdate", Type: field.TypeTime, Nullable: true},
		{Name: "age", Type: field.TypeInt, Nullable: true},
		{Name: "fully_onboarded", Type: field.TypeBool, Default: false},
		{Name: "phone_number_e164", Type: field.TypeString, Nullable: true},
		{Name: "country_code", Type: field.TypeString, Nullable: true},
		{Name: "phone_verified", Type: field.TypeBool, Nullable: true},
		{Name: "stripe_id", Type: field.TypeString, Unique: true, Nullable: true},
		{Name: "profile_profile_image", Type: field.TypeInt, Nullable: true},
		{Name: "user_profile", Type: field.TypeInt, Unique: true},
	}
	// ProfilesTable holds the schema information for the "profiles" table.
	ProfilesTable = &schema.Table{
		Name:       "profiles",
		Columns:    ProfilesColumns,
		PrimaryKey: []*schema.Column{ProfilesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "profiles_images_profile_image",
				Columns:    []*schema.Column{ProfilesColumns[11]},
				RefColumns: []*schema.Column{ImagesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "profiles_users_profile",
				Columns:    []*schema.Column{ProfilesColumns[12]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// PwaPushSubscriptionsColumns holds the columns for the "pwa_push_subscriptions" table.
	PwaPushSubscriptionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "endpoint", Type: field.TypeString},
		{Name: "p256dh", Type: field.TypeString},
		{Name: "auth", Type: field.TypeString},
		{Name: "profile_id", Type: field.TypeInt},
	}
	// PwaPushSubscriptionsTable holds the schema information for the "pwa_push_subscriptions" table.
	PwaPushSubscriptionsTable = &schema.Table{
		Name:       "pwa_push_subscriptions",
		Columns:    PwaPushSubscriptionsColumns,
		PrimaryKey: []*schema.Column{PwaPushSubscriptionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "pwa_push_subscriptions_profiles_pwa_push_subscriptions",
				Columns:    []*schema.Column{PwaPushSubscriptionsColumns[6]},
				RefColumns: []*schema.Column{ProfilesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "pwapushsubscription_profile_id_endpoint",
				Unique:  true,
				Columns: []*schema.Column{PwaPushSubscriptionsColumns[6], PwaPushSubscriptionsColumns[3]},
			},
		},
	}
	// RadacctColumns holds the columns for the "radacct" table.
	RadacctColumns = []*schema.Column{
		{Name: "radacctid", Type: field.TypeInt64, Increment: true},
		{Name: "acctsessionid", Type: field.TypeString, Size: 64},
		{Name: "acctuniqueid", Type: field.TypeString, Unique: true, Size: 32},
		{Name: "username", Type: field.TypeString, Size: 64},
		{Name: "acctstarttime", Type: field.TypeTime, Nullable: true},
		{Name: "acctstoptime", Type: field.TypeTime, Nullable: true},
		{Name: "acctsessiontime", Type: field.TypeUint32, Nullable: true},
		{Name: "acctinputoctets", Type: field.TypeInt64, Nullable: true},
		{Name: "acctoutputoctets", Type: field.TypeInt64, Nullable: true},
		{Name: "framedipaddress", Type: field.TypeString, Size: 15},
		{Name: "acctterminatecause", Type: field.TypeString, Size: 32},
	}
	// RadacctTable holds the schema information for the "radacct" table.
	RadacctTable = &schema.Table{
		Name:       "radacct",
		Columns:    RadacctColumns,
		PrimaryKey: []*schema.Column{RadacctColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "radacct_username",
				Unique:  false,
				Columns: []*schema.Column{RadacctColumns[3]},
			},
			{
				Name:    "radacct_acctstarttime",
				Unique:  false,
				Columns: []*schema.Column{RadacctColumns[4]},
			},
			{
				Name:    "radacct_acctstoptime",
				Unique:  false,
				Columns: []*schema.Column{RadacctColumns[5]},
			},
			{
				Name:    "radacct_framedipaddress",
				Unique:  false,
				Columns: []*schema.Column{RadacctColumns[9]},
			},
		},
	}
	// SentEmailsColumns holds the columns for the "sent_emails" table.
	SentEmailsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"partner_activity"}},
		{Name: "profile_sent_emails", Type: field.TypeInt},
	}
	// SentEmailsTable holds the schema information for the "sent_emails" table.
	SentEmailsTable = &schema.Table{
		Name:       "sent_emails",
		Columns:    SentEmailsColumns,
		PrimaryKey: []*schema.Column{SentEmailsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sent_emails_profiles_sent_emails",
				Columns:    []*schema.Column{SentEmailsColumns[4]},
				RefColumns: []*schema.Column{ProfilesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// TicketsColumns holds the columns for the "tickets" table.
	TicketsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "subject", Type: field.TypeString, Size: 255},
		{Name: "description", Type: field.TypeString, Size: 2147483647},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"open", "pending", "closed"}, Default: "open"},
		{Name: "priority", Type: field.TypeEnum, Enums: []string{"low", "medium", "high"}, Default: "medium"},
		{Name: "client_id", Type: field.TypeInt},
		{Name: "client_username", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// TicketsTable holds the schema information for the "tickets" table.
	TicketsTable = &schema.Table{
		Name:       "tickets",
		Columns:    TicketsColumns,
		PrimaryKey: []*schema.Column{TicketsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "ticket_client_id",
				Unique:  false,
				Columns: []*schema.Column{TicketsColumns[5]},
			},
			{
				Name:    "ticket_client_username",
				Unique:  false,
				Columns: []*schema.Column{TicketsColumns[6]},
			},
			{
				Name:    "ticket_status",
				Unique:  false,
				Columns: []*schema.Column{TicketsColumns[3]},
			},
			{
				Name:    "ticket_created_at",
				Unique:  false,
				Columns: []*schema.Column{TicketsColumns[7]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "password", Type: field.TypeString},
		{Name: "last_online", Type: field.TypeTime, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// EmailSubscriptionSubscriptionsColumns holds the columns for the "email_subscription_subscriptions" table.
	EmailSubscriptionSubscriptionsColumns = []*schema.Column{
		{Name: "email_subscription_id", Type: field.TypeInt},
		{Name: "email_subscription_type_id", Type: field.TypeInt},
	}
	// EmailSubscriptionSubscriptionsTable holds the schema information for the "email_subscription_subscriptions" table.
	EmailSubscriptionSubscriptionsTable = &schema.Table{
		Name:       "email_subscription_subscriptions",
		Columns:    EmailSubscriptionSubscriptionsColumns,
		PrimaryKey: []*schema.Column{EmailSubscriptionSubscriptionsColumns[0], EmailSubscriptionSubscriptionsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "email_subscription_subscriptions_email_subscription_id",
				Columns:    []*schema.Column{EmailSubscriptionSubscriptionsColumns[0]},
				RefColumns: []*schema.Column{EmailSubscriptionsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "email_subscription_subscriptions_email_subscription_type_id",
				Columns:    []*schema.Column{EmailSubscriptionSubscriptionsColumns[1]},
				RefColumns: []*schema.Column{EmailSubscriptionTypesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// MonthlySubscriptionBenefactorsColumns holds the columns for the "monthly_subscription_benefactors" table.
	MonthlySubscriptionBenefactorsColumns = []*schema.Column{
		{Name: "monthly_subscription_id", Type: field.TypeInt},
		{Name: "profile_id", Type: field.TypeInt},
	}
	// MonthlySubscriptionBenefactorsTable holds the schema information for the "monthly_subscription_benefactors" table.
	MonthlySubscriptionBenefactorsTable = &schema.Table{
		Name:       "monthly_subscription_benefactors",
		Columns:    MonthlySubscriptionBenefactorsColumns,
		PrimaryKey: []*schema.Column{MonthlySubscriptionBenefactorsColumns[0], MonthlySubscriptionBenefactorsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "monthly_subscription_benefactors_monthly_subscription_id",
				Columns:    []*schema.Column{MonthlySubscriptionBenefactorsColumns[0]},
				RefColumns: []*schema.Column{MonthlySubscriptionsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "monthly_subscription_benefactors_profile_id",
				Columns:    []*schema.Column{MonthlySubscriptionBenefactorsColumns[1]},
				RefColumns: []*schema.Column{ProfilesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// ProfileFriendsColumns holds the columns for the "profile_friends" table.
	ProfileFriendsColumns = []*schema.Column{
		{Name: "profile_id", Type: field.TypeInt},
		{Name: "friend_id", Type: field.TypeInt},
	}
	// ProfileFriendsTable holds the schema information for the "profile_friends" table.
	ProfileFriendsTable = &schema.Table{
		Name:       "profile_friends",
		Columns:    ProfileFriendsColumns,
		PrimaryKey: []*schema.Column{ProfileFriendsColumns[0], ProfileFriendsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "profile_friends_profile_id",
				Columns:    []*schema.Column{ProfileFriendsColumns[0]},
				RefColumns: []*schema.Column{ProfilesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "profile_friends_friend_id",
				Columns:    []*schema.Column{ProfileFriendsColumns[1]},
				RefColumns: []*schema.Column{ProfilesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ClientTxnTable,
		ClientsTable,
		EmailSubscriptionsTable,
		EmailSubscriptionTypesTable,
		EmojisTable,
		FcmSubscriptionsTable,
		FileStoragesTable,
		ImagesTable,
		ImageSizesTable,
		InvitationsTable,
		LastSeenOnlinesTable,
		MonthlySubscriptionsTable,
		NotificationsTable,
		NotificationPermissionsTable,
		NotificationTimesTable,
		PackagesTable,
		PhoneVerificationCodesTable,
		ProfilesTable,
		PwaPushSubscriptionsTable,
		RadacctTable,
		SentEmailsTable,
		TicketsTable,
		UsersTable,
		EmailSubscriptionSubscriptionsTable,
		MonthlySubscriptionBenefactorsTable,
		ProfileFriendsTable,
	}
)

func init() {
	ClientTxnTable.Annotation = &entsql.Annotation{
		Table: "client_txn",
	}
	ClientsTable.Annotation = &entsql.Annotation{
		Table: "clients",
	}
	FcmSubscriptionsTable.ForeignKeys[0].RefTable = ProfilesTable
	ImagesTable.ForeignKeys[0].RefTable = ProfilesTable
	ImageSizesTable.ForeignKeys[0].RefTable = ImagesTable
	ImageSizesTable.ForeignKeys[1].RefTable = FileStoragesTable
	InvitationsTable.ForeignKeys[0].RefTable = ProfilesTable
	LastSeenOnlinesTable.ForeignKeys[0].RefTable = UsersTable
	MonthlySubscriptionsTable.ForeignKeys[0].RefTable = ProfilesTable
	NotificationsTable.ForeignKeys[0].RefTable = ProfilesTable
	NotificationPermissionsTable.ForeignKeys[0].RefTable = ProfilesTable
	NotificationTimesTable.ForeignKeys[0].RefTable = ProfilesTable
	PackagesTable.Annotation = &entsql.Annotation{
		Table: "packages",
	}
	PhoneVerificationCodesTable.ForeignKeys[0].RefTable = ProfilesTable
	ProfilesTable.ForeignKeys[0].RefTable = ImagesTable
	ProfilesTable.ForeignKeys[1].RefTable = UsersTable
	PwaPushSubscriptionsTable.ForeignKeys[0].RefTable = ProfilesTable
	RadacctTable.Annotation = &entsql.Annotation{
		Table: "radacct",
	}
	SentEmailsTable.ForeignKeys[0].RefTable = ProfilesTable
	EmailSubscriptionSubscriptionsTable.ForeignKeys[0].RefTable = EmailSubscriptionsTable
	EmailSubscriptionSubscriptionsTable.ForeignKeys[1].RefTable = EmailSubscriptionTypesTable
	MonthlySubscriptionBenefactorsTable.ForeignKeys[0].RefTable = MonthlySubscriptionsTable
	MonthlySubscriptionBenefactorsTable.ForeignKeys[1].RefTable = ProfilesTable
	MonthlySubscriptionBenefactorsTable.Annotation = &entsql.Annotation{}
	ProfileFriendsTable.ForeignKeys[0].RefTable = ProfilesTable
	ProfileFriendsTable.ForeignKeys[1].RefTable = ProfilesTable
	ProfileFriendsTable.Annotation = &entsql.Annotation{}
}
