// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mikestefanello/pagoda/ent/clientuser"
	"github.com/mikestefanello/pagoda/ent/predicate"
)

// ClientUserUpdate is the builder for updating ClientUser entities.
type ClientUserUpdate struct {
	config
	hooks    []Hook
	mutation *ClientUserMutation
}

// Where appends a list predicates to the ClientUserUpdate builder.
func (cuu *ClientUserUpdate) Where(ps ...predicate.ClientUser) *ClientUserUpdate {
	cuu.mutation.Where(ps...)
	return cuu
}

// SetName sets the "name" field.
func (cuu *ClientUserUpdate) SetName(s string) *ClientUserUpdate {
	cuu.mutation.SetName(s)
	return cuu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (cuu *ClientUserUpdate) SetNillableName(s *string) *ClientUserUpdate {
	if s != nil {
		cuu.SetName(*s)
	}
	return cuu
}

// SetUsername sets the "username" field.
func (cuu *ClientUserUpdate) SetUsername(s string) *ClientUserUpdate {
	cuu.mutation.SetUsername(s)
	return cuu
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (cuu *ClientUserUpdate) SetNillableUsername(s *string) *ClientUserUpdate {
	if s != nil {
		cuu.SetUsername(*s)
	}
	return cuu
}

// SetPassword sets the "password" field.
func (cuu *ClientUserUpdate) SetPassword(s string) *ClientUserUpdate {
	cuu.mutation.SetPassword(s)
	return cuu
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (cuu *ClientUserUpdate) SetNillablePassword(s *string) *ClientUserUpdate {
	if s != nil {
		cuu.SetPassword(*s)
	}
	return cuu
}

// SetMobileNumber sets the "mobile_number" field.
func (cuu *ClientUserUpdate) SetMobileNumber(s string) *ClientUserUpdate {
	cuu.mutation.SetMobileNumber(s)
	return cuu
}

// SetNillableMobileNumber sets the "mobile_number" field if the given value is not nil.
func (cuu *ClientUserUpdate) SetNillableMobileNumber(s *string) *ClientUserUpdate {
	if s != nil {
		cuu.SetMobileNumber(*s)
	}
	return cuu
}

// SetEmail sets the "email" field.
func (cuu *ClientUserUpdate) SetEmail(s string) *ClientUserUpdate {
	cuu.mutation.SetEmail(s)
	return cuu
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (cuu *ClientUserUpdate) SetNillableEmail(s *string) *ClientUserUpdate {
	if s != nil {
		cuu.SetEmail(*s)
	}
	return cuu
}

// SetPhoto sets the "photo" field.
func (cuu *ClientUserUpdate) SetPhoto(s string) *ClientUserUpdate {
	cuu.mutation.SetPhoto(s)
	return cuu
}

// SetNillablePhoto sets the "photo" field if the given value is not nil.
func (cuu *ClientUserUpdate) SetNillablePhoto(s *string) *ClientUserUpdate {
	if s != nil {
		cuu.SetPhoto(*s)
	}
	return cuu
}

// ClearPhoto clears the value of the "photo" field.
func (cuu *ClientUserUpdate) ClearPhoto() *ClientUserUpdate {
	cuu.mutation.ClearPhoto()
	return cuu
}

// SetDescription sets the "description" field.
func (cuu *ClientUserUpdate) SetDescription(s string) *ClientUserUpdate {
	cuu.mutation.SetDescription(s)
	return cuu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (cuu *ClientUserUpdate) SetNillableDescription(s *string) *ClientUserUpdate {
	if s != nil {
		cuu.SetDescription(*s)
	}
	return cuu
}

// ClearDescription clears the value of the "description" field.
func (cuu *ClientUserUpdate) ClearDescription() *ClientUserUpdate {
	cuu.mutation.ClearDescription()
	return cuu
}

// SetBalance sets the "balance" field.
func (cuu *ClientUserUpdate) SetBalance(f float64) *ClientUserUpdate {
	cuu.mutation.ResetBalance()
	cuu.mutation.SetBalance(f)
	return cuu
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (cuu *ClientUserUpdate) SetNillableBalance(f *float64) *ClientUserUpdate {
	if f != nil {
		cuu.SetBalance(*f)
	}
	return cuu
}

// AddBalance adds f to the "balance" field.
func (cuu *ClientUserUpdate) AddBalance(f float64) *ClientUserUpdate {
	cuu.mutation.AddBalance(f)
	return cuu
}

// SetAddressLine1 sets the "address_line1" field.
func (cuu *ClientUserUpdate) SetAddressLine1(s string) *ClientUserUpdate {
	cuu.mutation.SetAddressLine1(s)
	return cuu
}

// SetNillableAddressLine1 sets the "address_line1" field if the given value is not nil.
func (cuu *ClientUserUpdate) SetNillableAddressLine1(s *string) *ClientUserUpdate {
	if s != nil {
		cuu.SetAddressLine1(*s)
	}
	return cuu
}

// ClearAddressLine1 clears the value of the "address_line1" field.
func (cuu *ClientUserUpdate) ClearAddressLine1() *ClientUserUpdate {
	cuu.mutation.ClearAddressLine1()
	return cuu
}

// SetAddressLine2 sets the "address_line2" field.
func (cuu *ClientUserUpdate) SetAddressLine2(s string) *ClientUserUpdate {
	cuu.mutation.SetAddressLine2(s)
	return cuu
}

// SetNillableAddressLine2 sets the "address_line2" field if the given value is not nil.
func (cuu *ClientUserUpdate) SetNillableAddressLine2(s *string) *ClientUserUpdate {
	if s != nil {
		cuu.SetAddressLine2(*s)
	}
	return cuu
}

// ClearAddressLine2 clears the value of the "address_line2" field.
func (cuu *ClientUserUpdate) ClearAddressLine2() *ClientUserUpdate {
	cuu.mutation.ClearAddressLine2()
	return cuu
}

// SetCity sets the "city" field.
func (cuu *ClientUserUpdate) SetCity(s string) *ClientUserUpdate {
	cuu.mutation.SetCity(s)
	return cuu
}

// SetNillableCity sets the "city" field if the given value is not nil.
func (cuu *ClientUserUpdate) SetNillableCity(s *string) *ClientUserUpdate {
	if s != nil {
		cuu.SetCity(*s)
	}
	return cuu
}

// ClearCity clears the value of the "city" field.
func (cuu *ClientUserUpdate) ClearCity() *ClientUserUpdate {
	cuu.mutation.ClearCity()
	return cuu
}

// SetDistrict sets the "district" field.
func (cuu *ClientUserUpdate) SetDistrict(s string) *ClientUserUpdate {
	cuu.mutation.SetDistrict(s)
	return cuu
}

// SetNillableDistrict sets the "district" field if the given value is not nil.
func (cuu *ClientUserUpdate) SetNillableDistrict(s *string) *ClientUserUpdate {
	if s != nil {
		cuu.SetDistrict(*s)
	}
	return cuu
}

// ClearDistrict clears the value of the "district" field.
func (cuu *ClientUserUpdate) ClearDistrict() *ClientUserUpdate {
	cuu.mutation.ClearDistrict()
	return cuu
}

// SetUpazila sets the "upazila" field.
func (cuu *ClientUserUpdate) SetUpazila(s string) *ClientUserUpdate {
	cuu.mutation.SetUpazila(s)
	return cuu
}

// SetNillableUpazila sets the "upazila" field if the given value is not nil.
func (cuu *ClientUserUpdate) SetNillableUpazila(s *string) *ClientUserUpdate {
	if s != nil {
		cuu.SetUpazila(*s)
	}
	return cuu
}

// ClearUpazila clears the value of the "upazila" field.
func (cuu *ClientUserUpdate) ClearUpazila() *ClientUserUpdate {
	cuu.mutation.ClearUpazila()
	return cuu
}

// SetUnionName sets the "union_name" field.
func (cuu *ClientUserUpdate) SetUnionName(s string) *ClientUserUpdate {
	cuu.mutation.SetUnionName(s)
	return cuu
}

// SetNillableUnionName sets the "union_name" field if the given value is not nil.
func (cuu *ClientUserUpdate) SetNillableUnionName(s *string) *ClientUserUpdate {
	if s != nil {
		cuu.SetUnionName(*s)
	}
	return cuu
}

// ClearUnionName clears the value of the "union_name" field.
func (cuu *ClientUserUpdate) ClearUnionName() *ClientUserUpdate {
	cuu.mutation.ClearUnionName()
	return cuu
}

// SetZip sets the "zip" field.
func (cuu *ClientUserUpdate) SetZip(s string) *ClientUserUpdate {
	cuu.mutation.SetZip(s)
	return cuu
}

// SetNillableZip sets the "zip" field if the given value is not nil.
func (cuu *ClientUserUpdate) SetNillableZip(s *string) *ClientUserUpdate {
	if s != nil {
		cuu.SetZip(*s)
	}
	return cuu
}

// ClearZip clears the value of the "zip" field.
func (cuu *ClientUserUpdate) ClearZip() *ClientUserUpdate {
	cuu.mutation.ClearZip()
	return cuu
}

// SetStatus sets the "status" field.
func (cuu *ClientUserUpdate) SetStatus(c clientuser.Status) *ClientUserUpdate {
	cuu.mutation.SetStatus(c)
	return cuu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (cuu *ClientUserUpdate) SetNillableStatus(c *clientuser.Status) *ClientUserUpdate {
	if c != nil {
		cuu.SetStatus(*c)
	}
	return cuu
}

// SetPaymentDate sets the "payment_date" field.
func (cuu *ClientUserUpdate) SetPaymentDate(t time.Time) *ClientUserUpdate {
	cuu.mutation.SetPaymentDate(t)
	return cuu
}

// SetNillablePaymentDate sets the "payment_date" field if the given value is not nil.
func (cuu *ClientUserUpdate) SetNillablePaymentDate(t *time.Time) *ClientUserUpdate {
	if t != nil {
		cuu.SetPaymentDate(*t)
	}
	return cuu
}

// ClearPaymentDate clears the value of the "payment_date" field.
func (cuu *ClientUserUpdate) ClearPaymentDate() *ClientUserUpdate {
	cuu.mutation.ClearPaymentDate()
	return cuu
}

// SetPaymentType sets the "payment_type" field.
func (cuu *ClientUserUpdate) SetPaymentType(s string) *ClientUserUpdate {
	cuu.mutation.SetPaymentType(s)
	return cuu
}

// SetNillablePaymentType sets the "payment_type" field if the given value is not nil.
func (cuu *ClientUserUpdate) SetNillablePaymentType(s *string) *ClientUserUpdate {
	if s != nil {
		cuu.SetPaymentType(*s)
	}
	return cuu
}

// ClearPaymentType clears the value of the "payment_type" field.
func (cuu *ClientUserUpdate) ClearPaymentType() *ClientUserUpdate {
	cuu.mutation.ClearPaymentType()
	return cuu
}

// SetAutoRenew sets the "auto_renew" field.
func (cuu *ClientUserUpdate) SetAutoRenew(b bool) *ClientUserUpdate {
	cuu.mutation.SetAutoRenew(b)
	return cuu
}

// SetNillableAutoRenew sets the "auto_renew" field if the given value is not nil.
func (cuu *ClientUserUpdate) SetNillableAutoRenew(b *bool) *ClientUserUpdate {
	if b != nil {
		cuu.SetAutoRenew(*b)
	}
	return cuu
}

// SetCName sets the "c_name" field.
func (cuu *ClientUserUpdate) SetCName(s string) *ClientUserUpdate {
	cuu.mutation.SetCName(s)
	return cuu
}

// SetNillableCName sets the "c_name" field if the given value is not nil.
func (cuu *ClientUserUpdate) SetNillableCName(s *string) *ClientUserUpdate {
	if s != nil {
		cuu.SetCName(*s)
	}
	return cuu
}

// SetVendorID sets the "vendor_id" field.
func (cuu *ClientUserUpdate) SetVendorID(i int) *ClientUserUpdate {
	cuu.mutation.ResetVendorID()
	cuu.mutation.SetVendorID(i)
	return cuu
}

// SetNillableVendorID sets the "vendor_id" field if the given value is not nil.
func (cuu *ClientUserUpdate) SetNillableVendorID(i *int) *ClientUserUpdate {
	if i != nil {
		cuu.SetVendorID(*i)
	}
	return cuu
}

// AddVendorID adds i to the "vendor_id" field.
func (cuu *ClientUserUpdate) AddVendorID(i int) *ClientUserUpdate {
	cuu.mutation.AddVendorID(i)
	return cuu
}

// SetPackagePool sets the "package_pool" field.
func (cuu *ClientUserUpdate) SetPackagePool(s string) *ClientUserUpdate {
	cuu.mutation.SetPackagePool(s)
	return cuu
}

// SetNillablePackagePool sets the "package_pool" field if the given value is not nil.
func (cuu *ClientUserUpdate) SetNillablePackagePool(s *string) *ClientUserUpdate {
	if s != nil {
		cuu.SetPackagePool(*s)
	}
	return cuu
}

// ClearPackagePool clears the value of the "package_pool" field.
func (cuu *ClientUserUpdate) ClearPackagePool() *ClientUserUpdate {
	cuu.mutation.ClearPackagePool()
	return cuu
}

// SetUserProfile sets the "user_profile" field.
func (cuu *ClientUserUpdate) SetUserProfile(s string) *ClientUserUpdate {
	cuu.mutation.SetUserProfile(s)
	return cuu
}

// SetNillableUserProfile sets the "user_profile" field if the given value is not nil.
func (cuu *ClientUserUpdate) SetNillableUserProfile(s *string) *ClientUserUpdate {
	if s != nil {
		cuu.SetUserProfile(*s)
	}
	return cuu
}

// ClearUserProfile clears the value of the "user_profile" field.
func (cuu *ClientUserUpdate) ClearUserProfile() *ClientUserUpdate {
	cuu.mutation.ClearUserProfile()
	return cuu
}

// SetNextUserProfile sets the "next_user_profile" field.
func (cuu *ClientUserUpdate) SetNextUserProfile(s string) *ClientUserUpdate {
	cuu.mutation.SetNextUserProfile(s)
	return cuu
}

// SetNillableNextUserProfile sets the "next_user_profile" field if the given value is not nil.
func (cuu *ClientUserUpdate) SetNillableNextUserProfile(s *string) *ClientUserUpdate {
	if s != nil {
		cuu.SetNextUserProfile(*s)
	}
	return cuu
}

// ClearNextUserProfile clears the value of the "next_user_profile" field.
func (cuu *ClientUserUpdate) ClearNextUserProfile() *ClientUserUpdate {
	cuu.mutation.ClearNextUserProfile()
	return cuu
}

// SetCreatedBy sets the "created_by" field.
func (cuu *ClientUserUpdate) SetCreatedBy(s string) *ClientUserUpdate {
	cuu.mutation.SetCreatedBy(s)
	return cuu
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (cuu *ClientUserUpdate) SetNillableCreatedBy(s *string) *ClientUserUpdate {
	if s != nil {
		cuu.SetCreatedBy(*s)
	}
	return cuu
}

// SetUpdatedBy sets the "updated_by" field.
func (cuu *ClientUserUpdate) SetUpdatedBy(s string) *ClientUserUpdate {
	cuu.mutation.SetUpdatedBy(s)
	return cuu
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (cuu *ClientUserUpdate) SetNillableUpdatedBy(s *string) *ClientUserUpdate {
	if s != nil {
		cuu.SetUpdatedBy(*s)
	}
	return cuu
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (cuu *ClientUserUpdate) ClearUpdatedBy() *ClientUserUpdate {
	cuu.mutation.ClearUpdatedBy()
	return cuu
}

// SetUpdatedDate sets the "updated_date" field.
func (cuu *ClientUserUpdate) SetUpdatedDate(t time.Time) *ClientUserUpdate {
	cuu.mutation.SetUpdatedDate(t)
	return cuu
}

// ClearUpdatedDate clears the value of the "updated_date" field.
func (cuu *ClientUserUpdate) ClearUpdatedDate() *ClientUserUpdate {
	cuu.mutation.ClearUpdatedDate()
	return cuu
}

// Mutation returns the ClientUserMutation object of the builder.
func (cuu *ClientUserUpdate) Mutation() *ClientUserMutation {
	return cuu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cuu *ClientUserUpdate) Save(ctx context.Context) (int, error) {
	cuu.defaults()
	return withHooks(ctx, cuu.sqlSave, cuu.mutation, cuu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cuu *ClientUserUpdate) SaveX(ctx context.Context) int {
	affected, err := cuu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cuu *ClientUserUpdate) Exec(ctx context.Context) error {
	_, err := cuu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuu *ClientUserUpdate) ExecX(ctx context.Context) {
	if err := cuu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cuu *ClientUserUpdate) defaults() {
	if _, ok := cuu.mutation.UpdatedDate(); !ok && !cuu.mutation.UpdatedDateCleared() {
		v := clientuser.UpdateDefaultUpdatedDate()
		cuu.mutation.SetUpdatedDate(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cuu *ClientUserUpdate) check() error {
	if v, ok := cuu.mutation.Name(); ok {
		if err := clientuser.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ClientUser.name": %w`, err)}
		}
	}
	if v, ok := cuu.mutation.Username(); ok {
		if err := clientuser.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "ClientUser.username": %w`, err)}
		}
	}
	if v, ok := cuu.mutation.Password(); ok {
		if err := clientuser.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "ClientUser.password": %w`, err)}
		}
	}
	if v, ok := cuu.mutation.MobileNumber(); ok {
		if err := clientuser.MobileNumberValidator(v); err != nil {
			return &ValidationError{Name: "mobile_number", err: fmt.Errorf(`ent: validator failed for field "ClientUser.mobile_number": %w`, err)}
		}
	}
	if v, ok := cuu.mutation.Email(); ok {
		if err := clientuser.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "ClientUser.email": %w`, err)}
		}
	}
	if v, ok := cuu.mutation.Photo(); ok {
		if err := clientuser.PhotoValidator(v); err != nil {
			return &ValidationError{Name: "photo", err: fmt.Errorf(`ent: validator failed for field "ClientUser.photo": %w`, err)}
		}
	}
	if v, ok := cuu.mutation.Balance(); ok {
		if err := clientuser.BalanceValidator(v); err != nil {
			return &ValidationError{Name: "balance", err: fmt.Errorf(`ent: validator failed for field "ClientUser.balance": %w`, err)}
		}
	}
	if v, ok := cuu.mutation.AddressLine1(); ok {
		if err := clientuser.AddressLine1Validator(v); err != nil {
			return &ValidationError{Name: "address_line1", err: fmt.Errorf(`ent: validator failed for field "ClientUser.address_line1": %w`, err)}
		}
	}
	if v, ok := cuu.mutation.AddressLine2(); ok {
		if err := clientuser.AddressLine2Validator(v); err != nil {
			return &ValidationError{Name: "address_line2", err: fmt.Errorf(`ent: validator failed for field "ClientUser.address_line2": %w`, err)}
		}
	}
	if v, ok := cuu.mutation.City(); ok {
		if err := clientuser.CityValidator(v); err != nil {
			return &ValidationError{Name: "city", err: fmt.Errorf(`ent: validator failed for field "ClientUser.city": %w`, err)}
		}
	}
	if v, ok := cuu.mutation.District(); ok {
		if err := clientuser.DistrictValidator(v); err != nil {
			return &ValidationError{Name: "district", err: fmt.Errorf(`ent: validator failed for field "ClientUser.district": %w`, err)}
		}
	}
	if v, ok := cuu.mutation.Upazila(); ok {
		if err := clientuser.UpazilaValidator(v); err != nil {
			return &ValidationError{Name: "upazila", err: fmt.Errorf(`ent: validator failed for field "ClientUser.upazila": %w`, err)}
		}
	}
	if v, ok := cuu.mutation.UnionName(); ok {
		if err := clientuser.UnionNameValidator(v); err != nil {
			return &ValidationError{Name: "union_name", err: fmt.Errorf(`ent: validator failed for field "ClientUser.union_name": %w`, err)}
		}
	}
	if v, ok := cuu.mutation.Zip(); ok {
		if err := clientuser.ZipValidator(v); err != nil {
			return &ValidationError{Name: "zip", err: fmt.Errorf(`ent: validator failed for field "ClientUser.zip": %w`, err)}
		}
	}
	if v, ok := cuu.mutation.Status(); ok {
		if err := clientuser.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ClientUser.status": %w`, err)}
		}
	}
	if v, ok := cuu.mutation.PaymentType(); ok {
		if err := clientuser.PaymentTypeValidator(v); err != nil {
			return &ValidationError{Name: "payment_type", err: fmt.Errorf(`ent: validator failed for field "ClientUser.payment_type": %w`, err)}
		}
	}
	if v, ok := cuu.mutation.CName(); ok {
		if err := clientuser.CNameValidator(v); err != nil {
			return &ValidationError{Name: "c_name", err: fmt.Errorf(`ent: validator failed for field "ClientUser.c_name": %w`, err)}
		}
	}
	if v, ok := cuu.mutation.VendorID(); ok {
		if err := clientuser.VendorIDValidator(v); err != nil {
			return &ValidationError{Name: "vendor_id", err: fmt.Errorf(`ent: validator failed for field "ClientUser.vendor_id": %w`, err)}
		}
	}
	if v, ok := cuu.mutation.PackagePool(); ok {
		if err := clientuser.PackagePoolValidator(v); err != nil {
			return &ValidationError{Name: "package_pool", err: fmt.Errorf(`ent: validator failed for field "ClientUser.package_pool": %w`, err)}
		}
	}
	if v, ok := cuu.mutation.UserProfile(); ok {
		if err := clientuser.UserProfileValidator(v); err != nil {
			return &ValidationError{Name: "user_profile", err: fmt.Errorf(`ent: validator failed for field "ClientUser.user_profile": %w`, err)}
		}
	}
	if v, ok := cuu.mutation.NextUserProfile(); ok {
		if err := clientuser.NextUserProfileValidator(v); err != nil {
			return &ValidationError{Name: "next_user_profile", err: fmt.Errorf(`ent: validator failed for field "ClientUser.next_user_profile": %w`, err)}
		}
	}
	if v, ok := cuu.mutation.CreatedBy(); ok {
		if err := clientuser.CreatedByValidator(v); err != nil {
			return &ValidationError{Name: "created_by", err: fmt.Errorf(`ent: validator failed for field "ClientUser.created_by": %w`, err)}
		}
	}
	if v, ok := cuu.mutation.UpdatedBy(); ok {
		if err := clientuser.UpdatedByValidator(v); err != nil {
			return &ValidationError{Name: "updated_by", err: fmt.Errorf(`ent: validator failed for field "ClientUser.updated_by": %w`, err)}
		}
	}
	return nil
}

func (cuu *ClientUserUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := cuu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(clientuser.Table, clientuser.Columns, sqlgraph.NewFieldSpec(clientuser.FieldID, field.TypeInt))
	if ps := cuu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuu.mutation.Name(); ok {
		_spec.SetField(clientuser.FieldName, field.TypeString, value)
	}
	if value, ok := cuu.mutation.Username(); ok {
		_spec.SetField(clientuser.FieldUsername, field.TypeString, value)
	}
	if value, ok := cuu.mutation.Password(); ok {
		_spec.SetField(clientuser.FieldPassword, field.TypeString, value)
	}
	if value, ok := cuu.mutation.MobileNumber(); ok {
		_spec.SetField(clientuser.FieldMobileNumber, field.TypeString, value)
	}
	if value, ok := cuu.mutation.Email(); ok {
		_spec.SetField(clientuser.FieldEmail, field.TypeString, value)
	}
	if value, ok := cuu.mutation.Photo(); ok {
		_spec.SetField(clientuser.FieldPhoto, field.TypeString, value)
	}
	if cuu.mutation.PhotoCleared() {
		_spec.ClearField(clientuser.FieldPhoto, field.TypeString)
	}
	if value, ok := cuu.mutation.Description(); ok {
		_spec.SetField(clientuser.FieldDescription, field.TypeString, value)
	}
	if cuu.mutation.DescriptionCleared() {
		_spec.ClearField(clientuser.FieldDescription, field.TypeString)
	}
	if value, ok := cuu.mutation.Balance(); ok {
		_spec.SetField(clientuser.FieldBalance, field.TypeFloat64, value)
	}
	if value, ok := cuu.mutation.AddedBalance(); ok {
		_spec.AddField(clientuser.FieldBalance, field.TypeFloat64, value)
	}
	if value, ok := cuu.mutation.AddressLine1(); ok {
		_spec.SetField(clientuser.FieldAddressLine1, field.TypeString, value)
	}
	if cuu.mutation.AddressLine1Cleared() {
		_spec.ClearField(clientuser.FieldAddressLine1, field.TypeString)
	}
	if value, ok := cuu.mutation.AddressLine2(); ok {
		_spec.SetField(clientuser.FieldAddressLine2, field.TypeString, value)
	}
	if cuu.mutation.AddressLine2Cleared() {
		_spec.ClearField(clientuser.FieldAddressLine2, field.TypeString)
	}
	if value, ok := cuu.mutation.City(); ok {
		_spec.SetField(clientuser.FieldCity, field.TypeString, value)
	}
	if cuu.mutation.CityCleared() {
		_spec.ClearField(clientuser.FieldCity, field.TypeString)
	}
	if value, ok := cuu.mutation.District(); ok {
		_spec.SetField(clientuser.FieldDistrict, field.TypeString, value)
	}
	if cuu.mutation.DistrictCleared() {
		_spec.ClearField(clientuser.FieldDistrict, field.TypeString)
	}
	if value, ok := cuu.mutation.Upazila(); ok {
		_spec.SetField(clientuser.FieldUpazila, field.TypeString, value)
	}
	if cuu.mutation.UpazilaCleared() {
		_spec.ClearField(clientuser.FieldUpazila, field.TypeString)
	}
	if value, ok := cuu.mutation.UnionName(); ok {
		_spec.SetField(clientuser.FieldUnionName, field.TypeString, value)
	}
	if cuu.mutation.UnionNameCleared() {
		_spec.ClearField(clientuser.FieldUnionName, field.TypeString)
	}
	if value, ok := cuu.mutation.Zip(); ok {
		_spec.SetField(clientuser.FieldZip, field.TypeString, value)
	}
	if cuu.mutation.ZipCleared() {
		_spec.ClearField(clientuser.FieldZip, field.TypeString)
	}
	if value, ok := cuu.mutation.Status(); ok {
		_spec.SetField(clientuser.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := cuu.mutation.PaymentDate(); ok {
		_spec.SetField(clientuser.FieldPaymentDate, field.TypeTime, value)
	}
	if cuu.mutation.PaymentDateCleared() {
		_spec.ClearField(clientuser.FieldPaymentDate, field.TypeTime)
	}
	if value, ok := cuu.mutation.PaymentType(); ok {
		_spec.SetField(clientuser.FieldPaymentType, field.TypeString, value)
	}
	if cuu.mutation.PaymentTypeCleared() {
		_spec.ClearField(clientuser.FieldPaymentType, field.TypeString)
	}
	if value, ok := cuu.mutation.AutoRenew(); ok {
		_spec.SetField(clientuser.FieldAutoRenew, field.TypeBool, value)
	}
	if value, ok := cuu.mutation.CName(); ok {
		_spec.SetField(clientuser.FieldCName, field.TypeString, value)
	}
	if value, ok := cuu.mutation.VendorID(); ok {
		_spec.SetField(clientuser.FieldVendorID, field.TypeInt, value)
	}
	if value, ok := cuu.mutation.AddedVendorID(); ok {
		_spec.AddField(clientuser.FieldVendorID, field.TypeInt, value)
	}
	if value, ok := cuu.mutation.PackagePool(); ok {
		_spec.SetField(clientuser.FieldPackagePool, field.TypeString, value)
	}
	if cuu.mutation.PackagePoolCleared() {
		_spec.ClearField(clientuser.FieldPackagePool, field.TypeString)
	}
	if value, ok := cuu.mutation.UserProfile(); ok {
		_spec.SetField(clientuser.FieldUserProfile, field.TypeString, value)
	}
	if cuu.mutation.UserProfileCleared() {
		_spec.ClearField(clientuser.FieldUserProfile, field.TypeString)
	}
	if value, ok := cuu.mutation.NextUserProfile(); ok {
		_spec.SetField(clientuser.FieldNextUserProfile, field.TypeString, value)
	}
	if cuu.mutation.NextUserProfileCleared() {
		_spec.ClearField(clientuser.FieldNextUserProfile, field.TypeString)
	}
	if value, ok := cuu.mutation.CreatedBy(); ok {
		_spec.SetField(clientuser.FieldCreatedBy, field.TypeString, value)
	}
	if value, ok := cuu.mutation.UpdatedBy(); ok {
		_spec.SetField(clientuser.FieldUpdatedBy, field.TypeString, value)
	}
	if cuu.mutation.UpdatedByCleared() {
		_spec.ClearField(clientuser.FieldUpdatedBy, field.TypeString)
	}
	if value, ok := cuu.mutation.UpdatedDate(); ok {
		_spec.SetField(clientuser.FieldUpdatedDate, field.TypeTime, value)
	}
	if cuu.mutation.UpdatedDateCleared() {
		_spec.ClearField(clientuser.FieldUpdatedDate, field.TypeTime)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cuu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{clientuser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	cuu.mutation.done = true
	return n, nil
}

// ClientUserUpdateOne is the builder for updating a single ClientUser entity.
type ClientUserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ClientUserMutation
}

// SetName sets the "name" field.
func (cuuo *ClientUserUpdateOne) SetName(s string) *ClientUserUpdateOne {
	cuuo.mutation.SetName(s)
	return cuuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (cuuo *ClientUserUpdateOne) SetNillableName(s *string) *ClientUserUpdateOne {
	if s != nil {
		cuuo.SetName(*s)
	}
	return cuuo
}

// SetUsername sets the "username" field.
func (cuuo *ClientUserUpdateOne) SetUsername(s string) *ClientUserUpdateOne {
	cuuo.mutation.SetUsername(s)
	return cuuo
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (cuuo *ClientUserUpdateOne) SetNillableUsername(s *string) *ClientUserUpdateOne {
	if s != nil {
		cuuo.SetUsername(*s)
	}
	return cuuo
}

// SetPassword sets the "password" field.
func (cuuo *ClientUserUpdateOne) SetPassword(s string) *ClientUserUpdateOne {
	cuuo.mutation.SetPassword(s)
	return cuuo
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (cuuo *ClientUserUpdateOne) SetNillablePassword(s *string) *ClientUserUpdateOne {
	if s != nil {
		cuuo.SetPassword(*s)
	}
	return cuuo
}

// SetMobileNumber sets the "mobile_number" field.
func (cuuo *ClientUserUpdateOne) SetMobileNumber(s string) *ClientUserUpdateOne {
	cuuo.mutation.SetMobileNumber(s)
	return cuuo
}

// SetNillableMobileNumber sets the "mobile_number" field if the given value is not nil.
func (cuuo *ClientUserUpdateOne) SetNillableMobileNumber(s *string) *ClientUserUpdateOne {
	if s != nil {
		cuuo.SetMobileNumber(*s)
	}
	return cuuo
}

// SetEmail sets the "email" field.
func (cuuo *ClientUserUpdateOne) SetEmail(s string) *ClientUserUpdateOne {
	cuuo.mutation.SetEmail(s)
	return cuuo
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (cuuo *ClientUserUpdateOne) SetNillableEmail(s *string) *ClientUserUpdateOne {
	if s != nil {
		cuuo.SetEmail(*s)
	}
	return cuuo
}

// SetPhoto sets the "photo" field.
func (cuuo *ClientUserUpdateOne) SetPhoto(s string) *ClientUserUpdateOne {
	cuuo.mutation.SetPhoto(s)
	return cuuo
}

// SetNillablePhoto sets the "photo" field if the given value is not nil.
func (cuuo *ClientUserUpdateOne) SetNillablePhoto(s *string) *ClientUserUpdateOne {
	if s != nil {
		cuuo.SetPhoto(*s)
	}
	return cuuo
}

// ClearPhoto clears the value of the "photo" field.
func (cuuo *ClientUserUpdateOne) ClearPhoto() *ClientUserUpdateOne {
	cuuo.mutation.ClearPhoto()
	return cuuo
}

// SetDescription sets the "description" field.
func (cuuo *ClientUserUpdateOne) SetDescription(s string) *ClientUserUpdateOne {
	cuuo.mutation.SetDescription(s)
	return cuuo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (cuuo *ClientUserUpdateOne) SetNillableDescription(s *string) *ClientUserUpdateOne {
	if s != nil {
		cuuo.SetDescription(*s)
	}
	return cuuo
}

// ClearDescription clears the value of the "description" field.
func (cuuo *ClientUserUpdateOne) ClearDescription() *ClientUserUpdateOne {
	cuuo.mutation.ClearDescription()
	return cuuo
}

// SetBalance sets the "balance" field.
func (cuuo *ClientUserUpdateOne) SetBalance(f float64) *ClientUserUpdateOne {
	cuuo.mutation.ResetBalance()
	cuuo.mutation.SetBalance(f)
	return cuuo
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (cuuo *ClientUserUpdateOne) SetNillableBalance(f *float64) *ClientUserUpdateOne {
	if f != nil {
		cuuo.SetBalance(*f)
	}
	return cuuo
}

// AddBalance adds f to the "balance" field.
func (cuuo *ClientUserUpdateOne) AddBalance(f float64) *ClientUserUpdateOne {
	cuuo.mutation.AddBalance(f)
	return cuuo
}

// SetAddressLine1 sets the "address_line1" field.
func (cuuo *ClientUserUpdateOne) SetAddressLine1(s string) *ClientUserUpdateOne {
	cuuo.mutation.SetAddressLine1(s)
	return cuuo
}

// SetNillableAddressLine1 sets the "address_line1" field if the given value is not nil.
func (cuuo *ClientUserUpdateOne) SetNillableAddressLine1(s *string) *ClientUserUpdateOne {
	if s != nil {
		cuuo.SetAddressLine1(*s)
	}
	return cuuo
}

// ClearAddressLine1 clears the value of the "address_line1" field.
func (cuuo *ClientUserUpdateOne) ClearAddressLine1() *ClientUserUpdateOne {
	cuuo.mutation.ClearAddressLine1()
	return cuuo
}

// SetAddressLine2 sets the "address_line2" field.
func (cuuo *ClientUserUpdateOne) SetAddressLine2(s string) *ClientUserUpdateOne {
	cuuo.mutation.SetAddressLine2(s)
	return cuuo
}

// SetNillableAddressLine2 sets the "address_line2" field if the given value is not nil.
func (cuuo *ClientUserUpdateOne) SetNillableAddressLine2(s *string) *ClientUserUpdateOne {
	if s != nil {
		cuuo.SetAddressLine2(*s)
	}
	return cuuo
}

// ClearAddressLine2 clears the value of the "address_line2" field.
func (cuuo *ClientUserUpdateOne) ClearAddressLine2() *ClientUserUpdateOne {
	cuuo.mutation.ClearAddressLine2()
	return cuuo
}

// SetCity sets the "city" field.
func (cuuo *ClientUserUpdateOne) SetCity(s string) *ClientUserUpdateOne {
	cuuo.mutation.SetCity(s)
	return cuuo
}

// SetNillableCity sets the "city" field if the given value is not nil.
func (cuuo *ClientUserUpdateOne) SetNillableCity(s *string) *ClientUserUpdateOne {
	if s != nil {
		cuuo.SetCity(*s)
	}
	return cuuo
}

// ClearCity clears the value of the "city" field.
func (cuuo *ClientUserUpdateOne) ClearCity() *ClientUserUpdateOne {
	cuuo.mutation.ClearCity()
	return cuuo
}

// SetDistrict sets the "district" field.
func (cuuo *ClientUserUpdateOne) SetDistrict(s string) *ClientUserUpdateOne {
	cuuo.mutation.SetDistrict(s)
	return cuuo
}

// SetNillableDistrict sets the "district" field if the given value is not nil.
func (cuuo *ClientUserUpdateOne) SetNillableDistrict(s *string) *ClientUserUpdateOne {
	if s != nil {
		cuuo.SetDistrict(*s)
	}
	return cuuo
}

// ClearDistrict clears the value of the "district" field.
func (cuuo *ClientUserUpdateOne) ClearDistrict() *ClientUserUpdateOne {
	cuuo.mutation.ClearDistrict()
	return cuuo
}

// SetUpazila sets the "upazila" field.
func (cuuo *ClientUserUpdateOne) SetUpazila(s string) *ClientUserUpdateOne {
	cuuo.mutation.SetUpazila(s)
	return cuuo
}

// SetNillableUpazila sets the "upazila" field if the given value is not nil.
func (cuuo *ClientUserUpdateOne) SetNillableUpazila(s *string) *ClientUserUpdateOne {
	if s != nil {
		cuuo.SetUpazila(*s)
	}
	return cuuo
}

// ClearUpazila clears the value of the "upazila" field.
func (cuuo *ClientUserUpdateOne) ClearUpazila() *ClientUserUpdateOne {
	cuuo.mutation.ClearUpazila()
	return cuuo
}

// SetUnionName sets the "union_name" field.
func (cuuo *ClientUserUpdateOne) SetUnionName(s string) *ClientUserUpdateOne {
	cuuo.mutation.SetUnionName(s)
	return cuuo
}

// SetNillableUnionName sets the "union_name" field if the given value is not nil.
func (cuuo *ClientUserUpdateOne) SetNillableUnionName(s *string) *ClientUserUpdateOne {
	if s != nil {
		cuuo.SetUnionName(*s)
	}
	return cuuo
}

// ClearUnionName clears the value of the "union_name" field.
func (cuuo *ClientUserUpdateOne) ClearUnionName() *ClientUserUpdateOne {
	cuuo.mutation.ClearUnionName()
	return cuuo
}

// SetZip sets the "zip" field.
func (cuuo *ClientUserUpdateOne) SetZip(s string) *ClientUserUpdateOne {
	cuuo.mutation.SetZip(s)
	return cuuo
}

// SetNillableZip sets the "zip" field if the given value is not nil.
func (cuuo *ClientUserUpdateOne) SetNillableZip(s *string) *ClientUserUpdateOne {
	if s != nil {
		cuuo.SetZip(*s)
	}
	return cuuo
}

// ClearZip clears the value of the "zip" field.
func (cuuo *ClientUserUpdateOne) ClearZip() *ClientUserUpdateOne {
	cuuo.mutation.ClearZip()
	return cuuo
}

// SetStatus sets the "status" field.
func (cuuo *ClientUserUpdateOne) SetStatus(c clientuser.Status) *ClientUserUpdateOne {
	cuuo.mutation.SetStatus(c)
	return cuuo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (cuuo *ClientUserUpdateOne) SetNillableStatus(c *clientuser.Status) *ClientUserUpdateOne {
	if c != nil {
		cuuo.SetStatus(*c)
	}
	return cuuo
}

// SetPaymentDate sets the "payment_date" field.
func (cuuo *ClientUserUpdateOne) SetPaymentDate(t time.Time) *ClientUserUpdateOne {
	cuuo.mutation.SetPaymentDate(t)
	return cuuo
}

// SetNillablePaymentDate sets the "payment_date" field if the given value is not nil.
func (cuuo *ClientUserUpdateOne) SetNillablePaymentDate(t *time.Time) *ClientUserUpdateOne {
	if t != nil {
		cuuo.SetPaymentDate(*t)
	}
	return cuuo
}

// ClearPaymentDate clears the value of the "payment_date" field.
func (cuuo *ClientUserUpdateOne) ClearPaymentDate() *ClientUserUpdateOne {
	cuuo.mutation.ClearPaymentDate()
	return cuuo
}

// SetPaymentType sets the "payment_type" field.
func (cuuo *ClientUserUpdateOne) SetPaymentType(s string) *ClientUserUpdateOne {
	cuuo.mutation.SetPaymentType(s)
	return cuuo
}

// SetNillablePaymentType sets the "payment_type" field if the given value is not nil.
func (cuuo *ClientUserUpdateOne) SetNillablePaymentType(s *string) *ClientUserUpdateOne {
	if s != nil {
		cuuo.SetPaymentType(*s)
	}
	return cuuo
}

// ClearPaymentType clears the value of the "payment_type" field.
func (cuuo *ClientUserUpdateOne) ClearPaymentType() *ClientUserUpdateOne {
	cuuo.mutation.ClearPaymentType()
	return cuuo
}

// SetAutoRenew sets the "auto_renew" field.
func (cuuo *ClientUserUpdateOne) SetAutoRenew(b bool) *ClientUserUpdateOne {
	cuuo.mutation.SetAutoRenew(b)
	return cuuo
}

// SetNillableAutoRenew sets the "auto_renew" field if the given value is not nil.
func (cuuo *ClientUserUpdateOne) SetNillableAutoRenew(b *bool) *ClientUserUpdateOne {
	if b != nil {
		cuuo.SetAutoRenew(*b)
	}
	return cuuo
}

// SetCName sets the "c_name" field.
func (cuuo *ClientUserUpdateOne) SetCName(s string) *ClientUserUpdateOne {
	cuuo.mutation.SetCName(s)
	return cuuo
}

// SetNillableCName sets the "c_name" field if the given value is not nil.
func (cuuo *ClientUserUpdateOne) SetNillableCName(s *string) *ClientUserUpdateOne {
	if s != nil {
		cuuo.SetCName(*s)
	}
	return cuuo
}

// SetVendorID sets the "vendor_id" field.
func (cuuo *ClientUserUpdateOne) SetVendorID(i int) *ClientUserUpdateOne {
	cuuo.mutation.ResetVendorID()
	cuuo.mutation.SetVendorID(i)
	return cuuo
}

// SetNillableVendorID sets the "vendor_id" field if the given value is not nil.
func (cuuo *ClientUserUpdateOne) SetNillableVendorID(i *int) *ClientUserUpdateOne {
	if i != nil {
		cuuo.SetVendorID(*i)
	}
	return cuuo
}

// AddVendorID adds i to the "vendor_id" field.
func (cuuo *ClientUserUpdateOne) AddVendorID(i int) *ClientUserUpdateOne {
	cuuo.mutation.AddVendorID(i)
	return cuuo
}

// SetPackagePool sets the "package_pool" field.
func (cuuo *ClientUserUpdateOne) SetPackagePool(s string) *ClientUserUpdateOne {
	cuuo.mutation.SetPackagePool(s)
	return cuuo
}

// SetNillablePackagePool sets the "package_pool" field if the given value is not nil.
func (cuuo *ClientUserUpdateOne) SetNillablePackagePool(s *string) *ClientUserUpdateOne {
	if s != nil {
		cuuo.SetPackagePool(*s)
	}
	return cuuo
}

// ClearPackagePool clears the value of the "package_pool" field.
func (cuuo *ClientUserUpdateOne) ClearPackagePool() *ClientUserUpdateOne {
	cuuo.mutation.ClearPackagePool()
	return cuuo
}

// SetUserProfile sets the "user_profile" field.
func (cuuo *ClientUserUpdateOne) SetUserProfile(s string) *ClientUserUpdateOne {
	cuuo.mutation.SetUserProfile(s)
	return cuuo
}

// SetNillableUserProfile sets the "user_profile" field if the given value is not nil.
func (cuuo *ClientUserUpdateOne) SetNillableUserProfile(s *string) *ClientUserUpdateOne {
	if s != nil {
		cuuo.SetUserProfile(*s)
	}
	return cuuo
}

// ClearUserProfile clears the value of the "user_profile" field.
func (cuuo *ClientUserUpdateOne) ClearUserProfile() *ClientUserUpdateOne {
	cuuo.mutation.ClearUserProfile()
	return cuuo
}

// SetNextUserProfile sets the "next_user_profile" field.
func (cuuo *ClientUserUpdateOne) SetNextUserProfile(s string) *ClientUserUpdateOne {
	cuuo.mutation.SetNextUserProfile(s)
	return cuuo
}

// SetNillableNextUserProfile sets the "next_user_profile" field if the given value is not nil.
func (cuuo *ClientUserUpdateOne) SetNillableNextUserProfile(s *string) *ClientUserUpdateOne {
	if s != nil {
		cuuo.SetNextUserProfile(*s)
	}
	return cuuo
}

// ClearNextUserProfile clears the value of the "next_user_profile" field.
func (cuuo *ClientUserUpdateOne) ClearNextUserProfile() *ClientUserUpdateOne {
	cuuo.mutation.ClearNextUserProfile()
	return cuuo
}

// SetCreatedBy sets the "created_by" field.
func (cuuo *ClientUserUpdateOne) SetCreatedBy(s string) *ClientUserUpdateOne {
	cuuo.mutation.SetCreatedBy(s)
	return cuuo
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (cuuo *ClientUserUpdateOne) SetNillableCreatedBy(s *string) *ClientUserUpdateOne {
	if s != nil {
		cuuo.SetCreatedBy(*s)
	}
	return cuuo
}

// SetUpdatedBy sets the "updated_by" field.
func (cuuo *ClientUserUpdateOne) SetUpdatedBy(s string) *ClientUserUpdateOne {
	cuuo.mutation.SetUpdatedBy(s)
	return cuuo
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (cuuo *ClientUserUpdateOne) SetNillableUpdatedBy(s *string) *ClientUserUpdateOne {
	if s != nil {
		cuuo.SetUpdatedBy(*s)
	}
	return cuuo
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (cuuo *ClientUserUpdateOne) ClearUpdatedBy() *ClientUserUpdateOne {
	cuuo.mutation.ClearUpdatedBy()
	return cuuo
}

// SetUpdatedDate sets the "updated_date" field.
func (cuuo *ClientUserUpdateOne) SetUpdatedDate(t time.Time) *ClientUserUpdateOne {
	cuuo.mutation.SetUpdatedDate(t)
	return cuuo
}

// ClearUpdatedDate clears the value of the "updated_date" field.
func (cuuo *ClientUserUpdateOne) ClearUpdatedDate() *ClientUserUpdateOne {
	cuuo.mutation.ClearUpdatedDate()
	return cuuo
}

// Mutation returns the ClientUserMutation object of the builder.
func (cuuo *ClientUserUpdateOne) Mutation() *ClientUserMutation {
	return cuuo.mutation
}

// Where appends a list predicates to the ClientUserUpdate builder.
func (cuuo *ClientUserUpdateOne) Where(ps ...predicate.ClientUser) *ClientUserUpdateOne {
	cuuo.mutation.Where(ps...)
	return cuuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuuo *ClientUserUpdateOne) Select(field string, fields ...string) *ClientUserUpdateOne {
	cuuo.fields = append([]string{field}, fields...)
	return cuuo
}

// Save executes the query and returns the updated ClientUser entity.
func (cuuo *ClientUserUpdateOne) Save(ctx context.Context) (*ClientUser, error) {
	cuuo.defaults()
	return withHooks(ctx, cuuo.sqlSave, cuuo.mutation, cuuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cuuo *ClientUserUpdateOne) SaveX(ctx context.Context) *ClientUser {
	node, err := cuuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuuo *ClientUserUpdateOne) Exec(ctx context.Context) error {
	_, err := cuuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuuo *ClientUserUpdateOne) ExecX(ctx context.Context) {
	if err := cuuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cuuo *ClientUserUpdateOne) defaults() {
	if _, ok := cuuo.mutation.UpdatedDate(); !ok && !cuuo.mutation.UpdatedDateCleared() {
		v := clientuser.UpdateDefaultUpdatedDate()
		cuuo.mutation.SetUpdatedDate(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cuuo *ClientUserUpdateOne) check() error {
	if v, ok := cuuo.mutation.Name(); ok {
		if err := clientuser.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ClientUser.name": %w`, err)}
		}
	}
	if v, ok := cuuo.mutation.Username(); ok {
		if err := clientuser.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "ClientUser.username": %w`, err)}
		}
	}
	if v, ok := cuuo.mutation.Password(); ok {
		if err := clientuser.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "ClientUser.password": %w`, err)}
		}
	}
	if v, ok := cuuo.mutation.MobileNumber(); ok {
		if err := clientuser.MobileNumberValidator(v); err != nil {
			return &ValidationError{Name: "mobile_number", err: fmt.Errorf(`ent: validator failed for field "ClientUser.mobile_number": %w`, err)}
		}
	}
	if v, ok := cuuo.mutation.Email(); ok {
		if err := clientuser.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "ClientUser.email": %w`, err)}
		}
	}
	if v, ok := cuuo.mutation.Photo(); ok {
		if err := clientuser.PhotoValidator(v); err != nil {
			return &ValidationError{Name: "photo", err: fmt.Errorf(`ent: validator failed for field "ClientUser.photo": %w`, err)}
		}
	}
	if v, ok := cuuo.mutation.Balance(); ok {
		if err := clientuser.BalanceValidator(v); err != nil {
			return &ValidationError{Name: "balance", err: fmt.Errorf(`ent: validator failed for field "ClientUser.balance": %w`, err)}
		}
	}
	if v, ok := cuuo.mutation.AddressLine1(); ok {
		if err := clientuser.AddressLine1Validator(v); err != nil {
			return &ValidationError{Name: "address_line1", err: fmt.Errorf(`ent: validator failed for field "ClientUser.address_line1": %w`, err)}
		}
	}
	if v, ok := cuuo.mutation.AddressLine2(); ok {
		if err := clientuser.AddressLine2Validator(v); err != nil {
			return &ValidationError{Name: "address_line2", err: fmt.Errorf(`ent: validator failed for field "ClientUser.address_line2": %w`, err)}
		}
	}
	if v, ok := cuuo.mutation.City(); ok {
		if err := clientuser.CityValidator(v); err != nil {
			return &ValidationError{Name: "city", err: fmt.Errorf(`ent: validator failed for field "ClientUser.city": %w`, err)}
		}
	}
	if v, ok := cuuo.mutation.District(); ok {
		if err := clientuser.DistrictValidator(v); err != nil {
			return &ValidationError{Name: "district", err: fmt.Errorf(`ent: validator failed for field "ClientUser.district": %w`, err)}
		}
	}
	if v, ok := cuuo.mutation.Upazila(); ok {
		if err := clientuser.UpazilaValidator(v); err != nil {
			return &ValidationError{Name: "upazila", err: fmt.Errorf(`ent: validator failed for field "ClientUser.upazila": %w`, err)}
		}
	}
	if v, ok := cuuo.mutation.UnionName(); ok {
		if err := clientuser.UnionNameValidator(v); err != nil {
			return &ValidationError{Name: "union_name", err: fmt.Errorf(`ent: validator failed for field "ClientUser.union_name": %w`, err)}
		}
	}
	if v, ok := cuuo.mutation.Zip(); ok {
		if err := clientuser.ZipValidator(v); err != nil {
			return &ValidationError{Name: "zip", err: fmt.Errorf(`ent: validator failed for field "ClientUser.zip": %w`, err)}
		}
	}
	if v, ok := cuuo.mutation.Status(); ok {
		if err := clientuser.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ClientUser.status": %w`, err)}
		}
	}
	if v, ok := cuuo.mutation.PaymentType(); ok {
		if err := clientuser.PaymentTypeValidator(v); err != nil {
			return &ValidationError{Name: "payment_type", err: fmt.Errorf(`ent: validator failed for field "ClientUser.payment_type": %w`, err)}
		}
	}
	if v, ok := cuuo.mutation.CName(); ok {
		if err := clientuser.CNameValidator(v); err != nil {
			return &ValidationError{Name: "c_name", err: fmt.Errorf(`ent: validator failed for field "ClientUser.c_name": %w`, err)}
		}
	}
	if v, ok := cuuo.mutation.VendorID(); ok {
		if err := clientuser.VendorIDValidator(v); err != nil {
			return &ValidationError{Name: "vendor_id", err: fmt.Errorf(`ent: validator failed for field "ClientUser.vendor_id": %w`, err)}
		}
	}
	if v, ok := cuuo.mutation.PackagePool(); ok {
		if err := clientuser.PackagePoolValidator(v); err != nil {
			return &ValidationError{Name: "package_pool", err: fmt.Errorf(`ent: validator failed for field "ClientUser.package_pool": %w`, err)}
		}
	}
	if v, ok := cuuo.mutation.UserProfile(); ok {
		if err := clientuser.UserProfileValidator(v); err != nil {
			return &ValidationError{Name: "user_profile", err: fmt.Errorf(`ent: validator failed for field "ClientUser.user_profile": %w`, err)}
		}
	}
	if v, ok := cuuo.mutation.NextUserProfile(); ok {
		if err := clientuser.NextUserProfileValidator(v); err != nil {
			return &ValidationError{Name: "next_user_profile", err: fmt.Errorf(`ent: validator failed for field "ClientUser.next_user_profile": %w`, err)}
		}
	}
	if v, ok := cuuo.mutation.CreatedBy(); ok {
		if err := clientuser.CreatedByValidator(v); err != nil {
			return &ValidationError{Name: "created_by", err: fmt.Errorf(`ent: validator failed for field "ClientUser.created_by": %w`, err)}
		}
	}
	if v, ok := cuuo.mutation.UpdatedBy(); ok {
		if err := clientuser.UpdatedByValidator(v); err != nil {
			return &ValidationError{Name: "updated_by", err: fmt.Errorf(`ent: validator failed for field "ClientUser.updated_by": %w`, err)}
		}
	}
	return nil
}

func (cuuo *ClientUserUpdateOne) sqlSave(ctx context.Context) (_node *ClientUser, err error) {
	if err := cuuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(clientuser.Table, clientuser.Columns, sqlgraph.NewFieldSpec(clientuser.FieldID, field.TypeInt))
	id, ok := cuuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ClientUser.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cuuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, clientuser.FieldID)
		for _, f := range fields {
			if !clientuser.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != clientuser.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuuo.mutation.Name(); ok {
		_spec.SetField(clientuser.FieldName, field.TypeString, value)
	}
	if value, ok := cuuo.mutation.Username(); ok {
		_spec.SetField(clientuser.FieldUsername, field.TypeString, value)
	}
	if value, ok := cuuo.mutation.Password(); ok {
		_spec.SetField(clientuser.FieldPassword, field.TypeString, value)
	}
	if value, ok := cuuo.mutation.MobileNumber(); ok {
		_spec.SetField(clientuser.FieldMobileNumber, field.TypeString, value)
	}
	if value, ok := cuuo.mutation.Email(); ok {
		_spec.SetField(clientuser.FieldEmail, field.TypeString, value)
	}
	if value, ok := cuuo.mutation.Photo(); ok {
		_spec.SetField(clientuser.FieldPhoto, field.TypeString, value)
	}
	if cuuo.mutation.PhotoCleared() {
		_spec.ClearField(clientuser.FieldPhoto, field.TypeString)
	}
	if value, ok := cuuo.mutation.Description(); ok {
		_spec.SetField(clientuser.FieldDescription, field.TypeString, value)
	}
	if cuuo.mutation.DescriptionCleared() {
		_spec.ClearField(clientuser.FieldDescription, field.TypeString)
	}
	if value, ok := cuuo.mutation.Balance(); ok {
		_spec.SetField(clientuser.FieldBalance, field.TypeFloat64, value)
	}
	if value, ok := cuuo.mutation.AddedBalance(); ok {
		_spec.AddField(clientuser.FieldBalance, field.TypeFloat64, value)
	}
	if value, ok := cuuo.mutation.AddressLine1(); ok {
		_spec.SetField(clientuser.FieldAddressLine1, field.TypeString, value)
	}
	if cuuo.mutation.AddressLine1Cleared() {
		_spec.ClearField(clientuser.FieldAddressLine1, field.TypeString)
	}
	if value, ok := cuuo.mutation.AddressLine2(); ok {
		_spec.SetField(clientuser.FieldAddressLine2, field.TypeString, value)
	}
	if cuuo.mutation.AddressLine2Cleared() {
		_spec.ClearField(clientuser.FieldAddressLine2, field.TypeString)
	}
	if value, ok := cuuo.mutation.City(); ok {
		_spec.SetField(clientuser.FieldCity, field.TypeString, value)
	}
	if cuuo.mutation.CityCleared() {
		_spec.ClearField(clientuser.FieldCity, field.TypeString)
	}
	if value, ok := cuuo.mutation.District(); ok {
		_spec.SetField(clientuser.FieldDistrict, field.TypeString, value)
	}
	if cuuo.mutation.DistrictCleared() {
		_spec.ClearField(clientuser.FieldDistrict, field.TypeString)
	}
	if value, ok := cuuo.mutation.Upazila(); ok {
		_spec.SetField(clientuser.FieldUpazila, field.TypeString, value)
	}
	if cuuo.mutation.UpazilaCleared() {
		_spec.ClearField(clientuser.FieldUpazila, field.TypeString)
	}
	if value, ok := cuuo.mutation.UnionName(); ok {
		_spec.SetField(clientuser.FieldUnionName, field.TypeString, value)
	}
	if cuuo.mutation.UnionNameCleared() {
		_spec.ClearField(clientuser.FieldUnionName, field.TypeString)
	}
	if value, ok := cuuo.mutation.Zip(); ok {
		_spec.SetField(clientuser.FieldZip, field.TypeString, value)
	}
	if cuuo.mutation.ZipCleared() {
		_spec.ClearField(clientuser.FieldZip, field.TypeString)
	}
	if value, ok := cuuo.mutation.Status(); ok {
		_spec.SetField(clientuser.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := cuuo.mutation.PaymentDate(); ok {
		_spec.SetField(clientuser.FieldPaymentDate, field.TypeTime, value)
	}
	if cuuo.mutation.PaymentDateCleared() {
		_spec.ClearField(clientuser.FieldPaymentDate, field.TypeTime)
	}
	if value, ok := cuuo.mutation.PaymentType(); ok {
		_spec.SetField(clientuser.FieldPaymentType, field.TypeString, value)
	}
	if cuuo.mutation.PaymentTypeCleared() {
		_spec.ClearField(clientuser.FieldPaymentType, field.TypeString)
	}
	if value, ok := cuuo.mutation.AutoRenew(); ok {
		_spec.SetField(clientuser.FieldAutoRenew, field.TypeBool, value)
	}
	if value, ok := cuuo.mutation.CName(); ok {
		_spec.SetField(clientuser.FieldCName, field.TypeString, value)
	}
	if value, ok := cuuo.mutation.VendorID(); ok {
		_spec.SetField(clientuser.FieldVendorID, field.TypeInt, value)
	}
	if value, ok := cuuo.mutation.AddedVendorID(); ok {
		_spec.AddField(clientuser.FieldVendorID, field.TypeInt, value)
	}
	if value, ok := cuuo.mutation.PackagePool(); ok {
		_spec.SetField(clientuser.FieldPackagePool, field.TypeString, value)
	}
	if cuuo.mutation.PackagePoolCleared() {
		_spec.ClearField(clientuser.FieldPackagePool, field.TypeString)
	}
	if value, ok := cuuo.mutation.UserProfile(); ok {
		_spec.SetField(clientuser.FieldUserProfile, field.TypeString, value)
	}
	if cuuo.mutation.UserProfileCleared() {
		_spec.ClearField(clientuser.FieldUserProfile, field.TypeString)
	}
	if value, ok := cuuo.mutation.NextUserProfile(); ok {
		_spec.SetField(clientuser.FieldNextUserProfile, field.TypeString, value)
	}
	if cuuo.mutation.NextUserProfileCleared() {
		_spec.ClearField(clientuser.FieldNextUserProfile, field.TypeString)
	}
	if value, ok := cuuo.mutation.CreatedBy(); ok {
		_spec.SetField(clientuser.FieldCreatedBy, field.TypeString, value)
	}
	if value, ok := cuuo.mutation.UpdatedBy(); ok {
		_spec.SetField(clientuser.FieldUpdatedBy, field.TypeString, value)
	}
	if cuuo.mutation.UpdatedByCleared() {
		_spec.ClearField(clientuser.FieldUpdatedBy, field.TypeString)
	}
	if value, ok := cuuo.mutation.UpdatedDate(); ok {
		_spec.SetField(clientuser.FieldUpdatedDate, field.TypeTime, value)
	}
	if cuuo.mutation.UpdatedDateCleared() {
		_spec.ClearField(clientuser.FieldUpdatedDate, field.TypeTime)
	}
	_node = &ClientUser{config: cuuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{clientuser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	cuuo.mutation.done = true
	return _node, nil
}
