// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mikestefanello/pagoda/ent/emailsubscription"
	"github.com/mikestefanello/pagoda/ent/emailsubscriptiontype"
)

// EmailSubscriptionCreate is the builder for creating a EmailSubscription entity.
type EmailSubscriptionCreate struct {
	config
	mutation *EmailSubscriptionMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (esc *EmailSubscriptionCreate) SetCreatedAt(t time.Time) *EmailSubscriptionCreate {
	esc.mutation.SetCreatedAt(t)
	return esc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (esc *EmailSubscriptionCreate) SetNillableCreatedAt(t *time.Time) *EmailSubscriptionCreate {
	if t != nil {
		esc.SetCreatedAt(*t)
	}
	return esc
}

// SetUpdatedAt sets the "updated_at" field.
func (esc *EmailSubscriptionCreate) SetUpdatedAt(t time.Time) *EmailSubscriptionCreate {
	esc.mutation.SetUpdatedAt(t)
	return esc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (esc *EmailSubscriptionCreate) SetNillableUpdatedAt(t *time.Time) *EmailSubscriptionCreate {
	if t != nil {
		esc.SetUpdatedAt(*t)
	}
	return esc
}

// SetEmail sets the "email" field.
func (esc *EmailSubscriptionCreate) SetEmail(s string) *EmailSubscriptionCreate {
	esc.mutation.SetEmail(s)
	return esc
}

// SetVerified sets the "verified" field.
func (esc *EmailSubscriptionCreate) SetVerified(b bool) *EmailSubscriptionCreate {
	esc.mutation.SetVerified(b)
	return esc
}

// SetNillableVerified sets the "verified" field if the given value is not nil.
func (esc *EmailSubscriptionCreate) SetNillableVerified(b *bool) *EmailSubscriptionCreate {
	if b != nil {
		esc.SetVerified(*b)
	}
	return esc
}

// SetConfirmationCode sets the "confirmation_code" field.
func (esc *EmailSubscriptionCreate) SetConfirmationCode(s string) *EmailSubscriptionCreate {
	esc.mutation.SetConfirmationCode(s)
	return esc
}

// SetLatitude sets the "latitude" field.
func (esc *EmailSubscriptionCreate) SetLatitude(f float64) *EmailSubscriptionCreate {
	esc.mutation.SetLatitude(f)
	return esc
}

// SetNillableLatitude sets the "latitude" field if the given value is not nil.
func (esc *EmailSubscriptionCreate) SetNillableLatitude(f *float64) *EmailSubscriptionCreate {
	if f != nil {
		esc.SetLatitude(*f)
	}
	return esc
}

// SetLongitude sets the "longitude" field.
func (esc *EmailSubscriptionCreate) SetLongitude(f float64) *EmailSubscriptionCreate {
	esc.mutation.SetLongitude(f)
	return esc
}

// SetNillableLongitude sets the "longitude" field if the given value is not nil.
func (esc *EmailSubscriptionCreate) SetNillableLongitude(f *float64) *EmailSubscriptionCreate {
	if f != nil {
		esc.SetLongitude(*f)
	}
	return esc
}

// AddSubscriptionIDs adds the "subscriptions" edge to the EmailSubscriptionType entity by IDs.
func (esc *EmailSubscriptionCreate) AddSubscriptionIDs(ids ...int) *EmailSubscriptionCreate {
	esc.mutation.AddSubscriptionIDs(ids...)
	return esc
}

// AddSubscriptions adds the "subscriptions" edges to the EmailSubscriptionType entity.
func (esc *EmailSubscriptionCreate) AddSubscriptions(e ...*EmailSubscriptionType) *EmailSubscriptionCreate {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return esc.AddSubscriptionIDs(ids...)
}

// Mutation returns the EmailSubscriptionMutation object of the builder.
func (esc *EmailSubscriptionCreate) Mutation() *EmailSubscriptionMutation {
	return esc.mutation
}

// Save creates the EmailSubscription in the database.
func (esc *EmailSubscriptionCreate) Save(ctx context.Context) (*EmailSubscription, error) {
	esc.defaults()
	return withHooks(ctx, esc.sqlSave, esc.mutation, esc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (esc *EmailSubscriptionCreate) SaveX(ctx context.Context) *EmailSubscription {
	v, err := esc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (esc *EmailSubscriptionCreate) Exec(ctx context.Context) error {
	_, err := esc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (esc *EmailSubscriptionCreate) ExecX(ctx context.Context) {
	if err := esc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (esc *EmailSubscriptionCreate) defaults() {
	if _, ok := esc.mutation.CreatedAt(); !ok {
		v := emailsubscription.DefaultCreatedAt()
		esc.mutation.SetCreatedAt(v)
	}
	if _, ok := esc.mutation.UpdatedAt(); !ok {
		v := emailsubscription.DefaultUpdatedAt()
		esc.mutation.SetUpdatedAt(v)
	}
	if _, ok := esc.mutation.Verified(); !ok {
		v := emailsubscription.DefaultVerified
		esc.mutation.SetVerified(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (esc *EmailSubscriptionCreate) check() error {
	if _, ok := esc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "EmailSubscription.created_at"`)}
	}
	if _, ok := esc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "EmailSubscription.updated_at"`)}
	}
	if _, ok := esc.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "EmailSubscription.email"`)}
	}
	if v, ok := esc.mutation.Email(); ok {
		if err := emailsubscription.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "EmailSubscription.email": %w`, err)}
		}
	}
	if _, ok := esc.mutation.Verified(); !ok {
		return &ValidationError{Name: "verified", err: errors.New(`ent: missing required field "EmailSubscription.verified"`)}
	}
	if _, ok := esc.mutation.ConfirmationCode(); !ok {
		return &ValidationError{Name: "confirmation_code", err: errors.New(`ent: missing required field "EmailSubscription.confirmation_code"`)}
	}
	if v, ok := esc.mutation.ConfirmationCode(); ok {
		if err := emailsubscription.ConfirmationCodeValidator(v); err != nil {
			return &ValidationError{Name: "confirmation_code", err: fmt.Errorf(`ent: validator failed for field "EmailSubscription.confirmation_code": %w`, err)}
		}
	}
	return nil
}

func (esc *EmailSubscriptionCreate) sqlSave(ctx context.Context) (*EmailSubscription, error) {
	if err := esc.check(); err != nil {
		return nil, err
	}
	_node, _spec := esc.createSpec()
	if err := sqlgraph.CreateNode(ctx, esc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	esc.mutation.id = &_node.ID
	esc.mutation.done = true
	return _node, nil
}

func (esc *EmailSubscriptionCreate) createSpec() (*EmailSubscription, *sqlgraph.CreateSpec) {
	var (
		_node = &EmailSubscription{config: esc.config}
		_spec = sqlgraph.NewCreateSpec(emailsubscription.Table, sqlgraph.NewFieldSpec(emailsubscription.FieldID, field.TypeInt))
	)
	if value, ok := esc.mutation.CreatedAt(); ok {
		_spec.SetField(emailsubscription.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := esc.mutation.UpdatedAt(); ok {
		_spec.SetField(emailsubscription.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := esc.mutation.Email(); ok {
		_spec.SetField(emailsubscription.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := esc.mutation.Verified(); ok {
		_spec.SetField(emailsubscription.FieldVerified, field.TypeBool, value)
		_node.Verified = value
	}
	if value, ok := esc.mutation.ConfirmationCode(); ok {
		_spec.SetField(emailsubscription.FieldConfirmationCode, field.TypeString, value)
		_node.ConfirmationCode = value
	}
	if value, ok := esc.mutation.Latitude(); ok {
		_spec.SetField(emailsubscription.FieldLatitude, field.TypeFloat64, value)
		_node.Latitude = value
	}
	if value, ok := esc.mutation.Longitude(); ok {
		_spec.SetField(emailsubscription.FieldLongitude, field.TypeFloat64, value)
		_node.Longitude = value
	}
	if nodes := esc.mutation.SubscriptionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   emailsubscription.SubscriptionsTable,
			Columns: emailsubscription.SubscriptionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(emailsubscriptiontype.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// EmailSubscriptionCreateBulk is the builder for creating many EmailSubscription entities in bulk.
type EmailSubscriptionCreateBulk struct {
	config
	err      error
	builders []*EmailSubscriptionCreate
}

// Save creates the EmailSubscription entities in the database.
func (escb *EmailSubscriptionCreateBulk) Save(ctx context.Context) ([]*EmailSubscription, error) {
	if escb.err != nil {
		return nil, escb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(escb.builders))
	nodes := make([]*EmailSubscription, len(escb.builders))
	mutators := make([]Mutator, len(escb.builders))
	for i := range escb.builders {
		func(i int, root context.Context) {
			builder := escb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EmailSubscriptionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, escb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, escb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, escb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (escb *EmailSubscriptionCreateBulk) SaveX(ctx context.Context) []*EmailSubscription {
	v, err := escb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (escb *EmailSubscriptionCreateBulk) Exec(ctx context.Context) error {
	_, err := escb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (escb *EmailSubscriptionCreateBulk) ExecX(ctx context.Context) {
	if err := escb.Exec(ctx); err != nil {
		panic(err)
	}
}
