// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mikestefanello/pagoda/ent/packageplan"
)

// PackagePlanCreate is the builder for creating a PackagePlan entity.
type PackagePlanCreate struct {
	config
	mutation *PackagePlanMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (ppc *PackagePlanCreate) SetName(s string) *PackagePlanCreate {
	ppc.mutation.SetName(s)
	return ppc
}

// SetPoolName sets the "pool_name" field.
func (ppc *PackagePlanCreate) SetPoolName(s string) *PackagePlanCreate {
	ppc.mutation.SetPoolName(s)
	return ppc
}

// SetNillablePoolName sets the "pool_name" field if the given value is not nil.
func (ppc *PackagePlanCreate) SetNillablePoolName(s *string) *PackagePlanCreate {
	if s != nil {
		ppc.SetPoolName(*s)
	}
	return ppc
}

// SetProfileName sets the "profile_name" field.
func (ppc *PackagePlanCreate) SetProfileName(s string) *PackagePlanCreate {
	ppc.mutation.SetProfileName(s)
	return ppc
}

// SetPrice sets the "price" field.
func (ppc *PackagePlanCreate) SetPrice(f float64) *PackagePlanCreate {
	ppc.mutation.SetPrice(f)
	return ppc
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (ppc *PackagePlanCreate) SetNillablePrice(f *float64) *PackagePlanCreate {
	if f != nil {
		ppc.SetPrice(*f)
	}
	return ppc
}

// SetCurrency sets the "currency" field.
func (ppc *PackagePlanCreate) SetCurrency(s string) *PackagePlanCreate {
	ppc.mutation.SetCurrency(s)
	return ppc
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (ppc *PackagePlanCreate) SetNillableCurrency(s *string) *PackagePlanCreate {
	if s != nil {
		ppc.SetCurrency(*s)
	}
	return ppc
}

// SetIsActive sets the "is_active" field.
func (ppc *PackagePlanCreate) SetIsActive(b bool) *PackagePlanCreate {
	ppc.mutation.SetIsActive(b)
	return ppc
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (ppc *PackagePlanCreate) SetNillableIsActive(b *bool) *PackagePlanCreate {
	if b != nil {
		ppc.SetIsActive(*b)
	}
	return ppc
}

// SetCreatedDate sets the "created_date" field.
func (ppc *PackagePlanCreate) SetCreatedDate(t time.Time) *PackagePlanCreate {
	ppc.mutation.SetCreatedDate(t)
	return ppc
}

// SetNillableCreatedDate sets the "created_date" field if the given value is not nil.
func (ppc *PackagePlanCreate) SetNillableCreatedDate(t *time.Time) *PackagePlanCreate {
	if t != nil {
		ppc.SetCreatedDate(*t)
	}
	return ppc
}

// SetID sets the "id" field.
func (ppc *PackagePlanCreate) SetID(i int) *PackagePlanCreate {
	ppc.mutation.SetID(i)
	return ppc
}

// Mutation returns the PackagePlanMutation object of the builder.
func (ppc *PackagePlanCreate) Mutation() *PackagePlanMutation {
	return ppc.mutation
}

// Save creates the PackagePlan in the database.
func (ppc *PackagePlanCreate) Save(ctx context.Context) (*PackagePlan, error) {
	ppc.defaults()
	return withHooks(ctx, ppc.sqlSave, ppc.mutation, ppc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ppc *PackagePlanCreate) SaveX(ctx context.Context) *PackagePlan {
	v, err := ppc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ppc *PackagePlanCreate) Exec(ctx context.Context) error {
	_, err := ppc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ppc *PackagePlanCreate) ExecX(ctx context.Context) {
	if err := ppc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ppc *PackagePlanCreate) defaults() {
	if _, ok := ppc.mutation.Price(); !ok {
		v := packageplan.DefaultPrice
		ppc.mutation.SetPrice(v)
	}
	if _, ok := ppc.mutation.Currency(); !ok {
		v := packageplan.DefaultCurrency
		ppc.mutation.SetCurrency(v)
	}
	if _, ok := ppc.mutation.IsActive(); !ok {
		v := packageplan.DefaultIsActive
		ppc.mutation.SetIsActive(v)
	}
	if _, ok := ppc.mutation.CreatedDate(); !ok {
		v := packageplan.DefaultCreatedDate()
		ppc.mutation.SetCreatedDate(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ppc *PackagePlanCreate) check() error {
	if _, ok := ppc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "PackagePlan.name"`)}
	}
	if v, ok := ppc.mutation.Name(); ok {
		if err := packageplan.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "PackagePlan.name": %w`, err)}
		}
	}
	if v, ok := ppc.mutation.PoolName(); ok {
		if err := packageplan.PoolNameValidator(v); err != nil {
			return &ValidationError{Name: "pool_name", err: fmt.Errorf(`ent: validator failed for field "PackagePlan.pool_name": %w`, err)}
		}
	}
	if _, ok := ppc.mutation.ProfileName(); !ok {
		return &ValidationError{Name: "profile_name", err: errors.New(`ent: missing required field "PackagePlan.profile_name"`)}
	}
	if v, ok := ppc.mutation.ProfileName(); ok {
		if err := packageplan.ProfileNameValidator(v); err != nil {
			return &ValidationError{Name: "profile_name", err: fmt.Errorf(`ent: validator failed for field "PackagePlan.profile_name": %w`, err)}
		}
	}
	if _, ok := ppc.mutation.Price(); !ok {
		return &ValidationError{Name: "price", err: errors.New(`ent: missing required field "PackagePlan.price"`)}
	}
	if _, ok := ppc.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "PackagePlan.currency"`)}
	}
	if v, ok := ppc.mutation.Currency(); ok {
		if err := packageplan.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "PackagePlan.currency": %w`, err)}
		}
	}
	if _, ok := ppc.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "PackagePlan.is_active"`)}
	}
	if _, ok := ppc.mutation.CreatedDate(); !ok {
		return &ValidationError{Name: "created_date", err: errors.New(`ent: missing required field "PackagePlan.created_date"`)}
	}
	if v, ok := ppc.mutation.ID(); ok {
		if err := packageplan.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "PackagePlan.id": %w`, err)}
		}
	}
	return nil
}

func (ppc *PackagePlanCreate) sqlSave(ctx context.Context) (*PackagePlan, error) {
	if err := ppc.check(); err != nil {
		return nil, err
	}
	_node, _spec := ppc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ppc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	ppc.mutation.id = &_node.ID
	ppc.mutation.done = true
	return _node, nil
}

func (ppc *PackagePlanCreate) createSpec() (*PackagePlan, *sqlgraph.CreateSpec) {
	var (
		_node = &PackagePlan{config: ppc.config}
		_spec = sqlgraph.NewCreateSpec(packageplan.Table, sqlgraph.NewFieldSpec(packageplan.FieldID, field.TypeInt))
	)
	if id, ok := ppc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := ppc.mutation.Name(); ok {
		_spec.SetField(packageplan.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := ppc.mutation.PoolName(); ok {
		_spec.SetField(packageplan.FieldPoolName, field.TypeString, value)
		_node.PoolName = value
	}
	if value, ok := ppc.mutation.ProfileName(); ok {
		_spec.SetField(packageplan.FieldProfileName, field.TypeString, value)
		_node.ProfileName = value
	}
	if value, ok := ppc.mutation.Price(); ok {
		_spec.SetField(packageplan.FieldPrice, field.TypeFloat64, value)
		_node.Price = value
	}
	if value, ok := ppc.mutation.Currency(); ok {
		_spec.SetField(packageplan.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := ppc.mutation.IsActive(); ok {
		_spec.SetField(packageplan.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := ppc.mutation.CreatedDate(); ok {
		_spec.SetField(packageplan.FieldCreatedDate, field.TypeTime, value)
		_node.CreatedDate = value
	}
	return _node, _spec
}

// PackagePlanCreateBulk is the builder for creating many PackagePlan entities in bulk.
type PackagePlanCreateBulk struct {
	config
	err      error
	builders []*PackagePlanCreate
}

// Save creates the PackagePlan entities in the database.
func (ppcb *PackagePlanCreateBulk) Save(ctx context.Context) ([]*PackagePlan, error) {
	if ppcb.err != nil {
		return nil, ppcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ppcb.builders))
	nodes := make([]*PackagePlan, len(ppcb.builders))
	mutators := make([]Mutator, len(ppcb.builders))
	for i := range ppcb.builders {
		func(i int, root context.Context) {
			builder := ppcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PackagePlanMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ppcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ppcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ppcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ppcb *PackagePlanCreateBulk) SaveX(ctx context.Context) []*PackagePlan {
	v, err := ppcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ppcb *PackagePlanCreateBulk) Exec(ctx context.Context) error {
	_, err := ppcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ppcb *PackagePlanCreateBulk) ExecX(ctx context.Context) {
	if err := ppcb.Exec(ctx); err != nil {
		panic(err)
	}
}
