// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mikestefanello/pagoda/ent/predicate"
	"github.com/mikestefanello/pagoda/ent/radacct"
)

// RadAcctDelete is the builder for deleting a RadAcct entity.
type RadAcctDelete struct {
	config
	hooks    []Hook
	mutation *RadAcctMutation
}

// Where appends a list predicates to the RadAcctDelete builder.
func (rad *RadAcctDelete) Where(ps ...predicate.RadAcct) *RadAcctDelete {
	rad.mutation.Where(ps...)
	return rad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (rad *RadAcctDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, rad.sqlExec, rad.mutation, rad.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (rad *RadAcctDelete) ExecX(ctx context.Context) int {
	n, err := rad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (rad *RadAcctDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(radacct.Table, sqlgraph.NewFieldSpec(radacct.FieldID, field.TypeInt64))
	if ps := rad.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, rad.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	rad.mutation.done = true
	return affected, err
}

// RadAcctDeleteOne is the builder for deleting a single RadAcct entity.
type RadAcctDeleteOne struct {
	rad *RadAcctDelete
}

// Where appends a list predicates to the RadAcctDelete builder.
func (rado *RadAcctDeleteOne) Where(ps ...predicate.RadAcct) *RadAcctDeleteOne {
	rado.rad.mutation.Where(ps...)
	return rado
}

// Exec executes the deletion query.
func (rado *RadAcctDeleteOne) Exec(ctx context.Context) error {
	n, err := rado.rad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{radacct.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (rado *RadAcctDeleteOne) ExecX(ctx context.Context) {
	if err := rado.Exec(ctx); err != nil {
		panic(err)
	}
}
