// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/mikestefanello/pagoda/ent/radacct"
)

// RadAcct is the model entity for the RadAcct schema.
type RadAcct struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// Acctsessionid holds the value of the "acctsessionid" field.
	Acctsessionid string `json:"acctsessionid,omitempty"`
	// Acctuniqueid holds the value of the "acctuniqueid" field.
	Acctuniqueid string `json:"acctuniqueid,omitempty"`
	// Username holds the value of the "username" field.
	Username string `json:"username,omitempty"`
	// Acctstarttime holds the value of the "acctstarttime" field.
	Acctstarttime *time.Time `json:"acctstarttime,omitempty"`
	// Acctstoptime holds the value of the "acctstoptime" field.
	Acctstoptime *time.Time `json:"acctstoptime,omitempty"`
	// Acctsessiontime holds the value of the "acctsessiontime" field.
	Acctsessiontime *uint32 `json:"acctsessiontime,omitempty"`
	// Acctinputoctets holds the value of the "acctinputoctets" field.
	Acctinputoctets *int64 `json:"acctinputoctets,omitempty"`
	// Acctoutputoctets holds the value of the "acctoutputoctets" field.
	Acctoutputoctets *int64 `json:"acctoutputoctets,omitempty"`
	// Framedipaddress holds the value of the "framedipaddress" field.
	Framedipaddress string `json:"framedipaddress,omitempty"`
	// Acctterminatecause holds the value of the "acctterminatecause" field.
	Acctterminatecause string `json:"acctterminatecause,omitempty"`
	selectValues       sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RadAcct) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case radacct.FieldID, radacct.FieldAcctsessiontime, radacct.FieldAcctinputoctets, radacct.FieldAcctoutputoctets:
			values[i] = new(sql.NullInt64)
		case radacct.FieldAcctsessionid, radacct.FieldAcctuniqueid, radacct.FieldUsername, radacct.FieldFramedipaddress, radacct.FieldAcctterminatecause:
			values[i] = new(sql.NullString)
		case radacct.FieldAcctstarttime, radacct.FieldAcctstoptime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RadAcct fields.
func (ra *RadAcct) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case radacct.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ra.ID = int64(value.Int64)
		case radacct.FieldAcctsessionid:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field acctsessionid", values[i])
			} else if value.Valid {
				ra.Acctsessionid = value.String
			}
		case radacct.FieldAcctuniqueid:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field acctuniqueid", values[i])
			} else if value.Valid {
				ra.Acctuniqueid = value.String
			}
		case radacct.FieldUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field username", values[i])
			} else if value.Valid {
				ra.Username = value.String
			}
		case radacct.FieldAcctstarttime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field acctstarttime", values[i])
			} else if value.Valid {
				ra.Acctstarttime = new(time.Time)
				*ra.Acctstarttime = value.Time
			}
		case radacct.FieldAcctstoptime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field acctstoptime", values[i])
			} else if value.Valid {
				ra.Acctstoptime = new(time.Time)
				*ra.Acctstoptime = value.Time
			}
		case radacct.FieldAcctsessiontime:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field acctsessiontime", values[i])
			} else if value.Valid {
				ra.Acctsessiontime = new(uint32)
				*ra.Acctsessiontime = uint32(value.Int64)
			}
		case radacct.FieldAcctinputoctets:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field acctinputoctets", values[i])
			} else if value.Valid {
				ra.Acctinputoctets = new(int64)
				*ra.Acctinputoctets = value.Int64
			}
		case radacct.FieldAcctoutputoctets:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field acctoutputoctets", values[i])
			} else if value.Valid {
				ra.Acctoutputoctets = new(int64)
				*ra.Acctoutputoctets = value.Int64
			}
		case radacct.FieldFramedipaddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field framedipaddress", values[i])
			} else if value.Valid {
				ra.Framedipaddress = value.String
			}
		case radacct.FieldAcctterminatecause:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field acctterminatecause", values[i])
			} else if value.Valid {
				ra.Acctterminatecause = value.String
			}
		default:
			ra.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RadAcct.
// This includes values selected through modifiers, order, etc.
func (ra *RadAcct) Value(name string) (ent.Value, error) {
	return ra.selectValues.Get(name)
}

// Update returns a builder for updating this RadAcct.
// Note that you need to call RadAcct.Unwrap() before calling this method if this RadAcct
// was returned from a transaction, and the transaction was committed or rolled back.
func (ra *RadAcct) Update() *RadAcctUpdateOne {
	return NewRadAcctClient(ra.config).UpdateOne(ra)
}

// Unwrap unwraps the RadAcct entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ra *RadAcct) Unwrap() *RadAcct {
	_tx, ok := ra.config.driver.(*txDriver)
	if !ok {
		panic("ent: RadAcct is not a transactional entity")
	}
	ra.config.driver = _tx.drv
	return ra
}

// String implements the fmt.Stringer.
func (ra *RadAcct) String() string {
	var builder strings.Builder
	builder.WriteString("RadAcct(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ra.ID))
	builder.WriteString("acctsessionid=")
	builder.WriteString(ra.Acctsessionid)
	builder.WriteString(", ")
	builder.WriteString("acctuniqueid=")
	builder.WriteString(ra.Acctuniqueid)
	builder.WriteString(", ")
	builder.WriteString("username=")
	builder.WriteString(ra.Username)
	builder.WriteString(", ")
	if v := ra.Acctstarttime; v != nil {
		builder.WriteString("acctstarttime=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := ra.Acctstoptime; v != nil {
		builder.WriteString("acctstoptime=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := ra.Acctsessiontime; v != nil {
		builder.WriteString("acctsessiontime=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := ra.Acctinputoctets; v != nil {
		builder.WriteString("acctinputoctets=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := ra.Acctoutputoctets; v != nil {
		builder.WriteString("acctoutputoctets=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("framedipaddress=")
	builder.WriteString(ra.Framedipaddress)
	builder.WriteString(", ")
	builder.WriteString("acctterminatecause=")
	builder.WriteString(ra.Acctterminatecause)
	builder.WriteByte(')')
	return builder.String()
}

// RadAccts is a parsable slice of RadAcct.
type RadAccts []*RadAcct
