// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mikestefanello/pagoda/ent/profile"
	"github.com/mikestefanello/pagoda/ent/sentemail"
)

// SentEmailCreate is the builder for creating a SentEmail entity.
type SentEmailCreate struct {
	config
	mutation *SentEmailMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (sec *SentEmailCreate) SetCreatedAt(t time.Time) *SentEmailCreate {
	sec.mutation.SetCreatedAt(t)
	return sec
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (sec *SentEmailCreate) SetNillableCreatedAt(t *time.Time) *SentEmailCreate {
	if t != nil {
		sec.SetCreatedAt(*t)
	}
	return sec
}

// SetUpdatedAt sets the "updated_at" field.
func (sec *SentEmailCreate) SetUpdatedAt(t time.Time) *SentEmailCreate {
	sec.mutation.SetUpdatedAt(t)
	return sec
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (sec *SentEmailCreate) SetNillableUpdatedAt(t *time.Time) *SentEmailCreate {
	if t != nil {
		sec.SetUpdatedAt(*t)
	}
	return sec
}

// SetType sets the "type" field.
func (sec *SentEmailCreate) SetType(s sentemail.Type) *SentEmailCreate {
	sec.mutation.SetType(s)
	return sec
}

// SetProfileID sets the "profile" edge to the Profile entity by ID.
func (sec *SentEmailCreate) SetProfileID(id int) *SentEmailCreate {
	sec.mutation.SetProfileID(id)
	return sec
}

// SetProfile sets the "profile" edge to the Profile entity.
func (sec *SentEmailCreate) SetProfile(p *Profile) *SentEmailCreate {
	return sec.SetProfileID(p.ID)
}

// Mutation returns the SentEmailMutation object of the builder.
func (sec *SentEmailCreate) Mutation() *SentEmailMutation {
	return sec.mutation
}

// Save creates the SentEmail in the database.
func (sec *SentEmailCreate) Save(ctx context.Context) (*SentEmail, error) {
	sec.defaults()
	return withHooks(ctx, sec.sqlSave, sec.mutation, sec.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sec *SentEmailCreate) SaveX(ctx context.Context) *SentEmail {
	v, err := sec.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sec *SentEmailCreate) Exec(ctx context.Context) error {
	_, err := sec.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sec *SentEmailCreate) ExecX(ctx context.Context) {
	if err := sec.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sec *SentEmailCreate) defaults() {
	if _, ok := sec.mutation.CreatedAt(); !ok {
		v := sentemail.DefaultCreatedAt()
		sec.mutation.SetCreatedAt(v)
	}
	if _, ok := sec.mutation.UpdatedAt(); !ok {
		v := sentemail.DefaultUpdatedAt()
		sec.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sec *SentEmailCreate) check() error {
	if _, ok := sec.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SentEmail.created_at"`)}
	}
	if _, ok := sec.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SentEmail.updated_at"`)}
	}
	if _, ok := sec.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "SentEmail.type"`)}
	}
	if v, ok := sec.mutation.GetType(); ok {
		if err := sentemail.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "SentEmail.type": %w`, err)}
		}
	}
	if len(sec.mutation.ProfileIDs()) == 0 {
		return &ValidationError{Name: "profile", err: errors.New(`ent: missing required edge "SentEmail.profile"`)}
	}
	return nil
}

func (sec *SentEmailCreate) sqlSave(ctx context.Context) (*SentEmail, error) {
	if err := sec.check(); err != nil {
		return nil, err
	}
	_node, _spec := sec.createSpec()
	if err := sqlgraph.CreateNode(ctx, sec.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	sec.mutation.id = &_node.ID
	sec.mutation.done = true
	return _node, nil
}

func (sec *SentEmailCreate) createSpec() (*SentEmail, *sqlgraph.CreateSpec) {
	var (
		_node = &SentEmail{config: sec.config}
		_spec = sqlgraph.NewCreateSpec(sentemail.Table, sqlgraph.NewFieldSpec(sentemail.FieldID, field.TypeInt))
	)
	if value, ok := sec.mutation.CreatedAt(); ok {
		_spec.SetField(sentemail.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := sec.mutation.UpdatedAt(); ok {
		_spec.SetField(sentemail.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := sec.mutation.GetType(); ok {
		_spec.SetField(sentemail.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if nodes := sec.mutation.ProfileIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sentemail.ProfileTable,
			Columns: []string{sentemail.ProfileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(profile.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.profile_sent_emails = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SentEmailCreateBulk is the builder for creating many SentEmail entities in bulk.
type SentEmailCreateBulk struct {
	config
	err      error
	builders []*SentEmailCreate
}

// Save creates the SentEmail entities in the database.
func (secb *SentEmailCreateBulk) Save(ctx context.Context) ([]*SentEmail, error) {
	if secb.err != nil {
		return nil, secb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(secb.builders))
	nodes := make([]*SentEmail, len(secb.builders))
	mutators := make([]Mutator, len(secb.builders))
	for i := range secb.builders {
		func(i int, root context.Context) {
			builder := secb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SentEmailMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, secb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, secb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, secb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (secb *SentEmailCreateBulk) SaveX(ctx context.Context) []*SentEmail {
	v, err := secb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (secb *SentEmailCreateBulk) Exec(ctx context.Context) error {
	_, err := secb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (secb *SentEmailCreateBulk) ExecX(ctx context.Context) {
	if err := secb.Exec(ctx); err != nil {
		panic(err)
	}
}
