// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/mikestefanello/pagoda/pkg/controller"

func NavbarPWAMobileInstallButton(page *controller.Page) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div id=\"navbar-pwa-install-button\"></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = InitPwaInstallButton("navbar-pwa-install-button", "navbar").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func PWAMobileInstallButton(page *controller.Page) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div id=\"mobile-pwa-install-button\"></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = InitPwaInstallButton("mobile-pwa-install-button", "mobile").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func InitPwaInstallButton(elemID, position string) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_InitPwaInstallButton_0d99`,
		Function: `function __templ_InitPwaInstallButton_0d99(elemID, position){renderSvelteComponent('PwaInstallButton', elemID, {
		"position": position,
	});
}`,
		Call:       templ.SafeScript(`__templ_InitPwaInstallButton_0d99`, elemID, position),
		CallInline: templ.SafeScriptInline(`__templ_InitPwaInstallButton_0d99`, elemID, position),
	}
}

func HideIfStandalone(elementId string) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_HideIfStandalone_640c`,
		Function: `function __templ_HideIfStandalone_640c(elementId){function isPwaStandalone() {
      return (window.matchMedia('(display-mode: standalone)').matches) || (window.navigator.standalone) || (document.referrer.includes('android-app://'));
    }

	if (!isPwaStandalone()) {
		document.getElementById(elementId).style.display = 'block';
	}
}`,
		Call:       templ.SafeScript(`__templ_HideIfStandalone_640c`, elementId),
		CallInline: templ.SafeScriptInline(`__templ_HideIfStandalone_640c`, elementId),
	}
}

func ShowIfStandalone(elementId string) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_ShowIfStandalone_a665`,
		Function: `function __templ_ShowIfStandalone_a665(elementId){function isPwaStandalone() {
      return (window.matchMedia('(display-mode: standalone)').matches) || (window.navigator.standalone) || (document.referrer.includes('android-app://'));
    }

	if (isPwaStandalone()) {
		document.getElementById(elementId).style.display = 'block';
	}
}`,
		Call:       templ.SafeScript(`__templ_ShowIfStandalone_a665`, elementId),
		CallInline: templ.SafeScriptInline(`__templ_ShowIfStandalone_a665`, elementId),
	}
}

var _ = templruntime.GeneratedTemplate
